import { db } from "@/db";
import { GroceryItem } from "@/types/meals";
import { groceryCategories } from "@/data/meals";

export interface GroceryInput {
  name: string;
  category?: string;
  aisle?: string;
  quantity?: string;
  notes?: string;
  priority?: "low" | "medium" | "high";
  needed?: boolean;
  source?: string;
  autoGenerated?: boolean;
  emoji?: string;
}

const normalizeName = (name: string) => name.toLowerCase().replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim();

export async function upsertGroceryItem(input: GroceryInput): Promise<GroceryItem> {
  const trimmed = input.name.trim();
  const category = input.category || "pantry";
  const catDef = groceryCategories.find(c => c.id === category);
  const itemEmoji = input.emoji || catDef?.emoji || "📦";
  const aisle = input.aisle || catDef?.aisles?.[0]?.split('-')[0] || "1";
  const quantity = input.quantity?.trim() || "";
  const notes = input.notes?.trim() || "";
  const priority = input.priority || "medium";
  const source = input.source || "manual";
  const autoGenerated = input.autoGenerated ?? false;

  const raw = await db.selectGrocery();
  const existing = raw.find((g: any) => g.name && normalizeName(g.name) === normalizeName(trimmed));

  if (existing) {
    const quantityFinal = quantity || existing.quantity || "";
    const notesFinal = notes || existing.notes || "";
    await db.upsertGroceryItem({ ...existing, needed: true, quantity: quantityFinal, notes: notesFinal });
    return {
      id: existing.id,
      name: existing.name || trimmed,
      emoji: existing.emoji || itemEmoji,
      category: existing.category || category,
      aisle: existing.aisle || aisle,
      quantity: quantityFinal,
      notes: notesFinal,
      priority: existing.priority || priority,
      needed: true,
      manualOverride: existing.manualOverride,
      lastSyncedAt: existing.lastSyncedAt,
      source: existing.source || source,
      autoGenerated: existing.autoGenerated ?? autoGenerated,
      quantityValue: existing.quantityValue,
      unit: existing.unit,
      pinned: existing.pinned,
      userId: existing.userId,
      updatedAt: existing.updatedAt,
    };
  }

  const newItem: GroceryItem = {
    id: Date.now(),
    name: trimmed,
    emoji: itemEmoji,
    category,
    aisle,
    quantity,
    notes,
    priority,
    needed: true,
    source,
    autoGenerated,
  };
  await db.upsertGroceryItem({ name: trimmed, category, aisle, quantity, notes, priority, needed: true, source, autoGenerated, emoji: itemEmoji });
  return newItem;
}
