"use client";
import { useState, useMemo } from "react";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import { groceryCategories, groceryPresets } from "@/data/meals";
import { GroceryItem } from "@/types/meals";

const PRESETS_PER_PAGE = 12;

export default function GroceryTab({
  groceryItems,
  setGroceryItems,
  activeCategory,
  setActiveCategory,
  isSyncing,
  recentlyBought,
  clearRecentlyBought,
  addGroceryItem,
  toggleGroceryNeeded,
  deleteGroceryItem,
  updateGroceryItem,
  syncMealToGrocery,
  syncPantryToGrocery,
}: any) {
  const [newGroceryItem, setNewGroceryItem] = useState("");
  const [newGroceryCategory, setNewGroceryCategory] = useState("pantry");
  const [newGroceryPriority, setNewGroceryPriority] = useState<"low" | "medium" | "high">("medium");
  const [editingGroceryId, setEditingGroceryId] = useState<number | null>(null);
  const [editName, setEditName] = useState("");
  const [editQuantity, setEditQuantity] = useState("");
  const [editNotes, setEditNotes] = useState("");
  const [presetCategory, setPresetCategory] = useState<string>("produce");
  const [showAllPresets, setShowAllPresets] = useState(false);

  const handleAdd = () => {
    if (!newGroceryItem.trim()) return;
    addGroceryItem(newGroceryItem, newGroceryCategory, newGroceryPriority);
    setNewGroceryItem("");
  };

  const handlePresetTap = (preset: { name: string; emoji: string; category: string }) => {
    addGroceryItem(preset.name, preset.category, "medium", preset.emoji);
  };

  const handleRecentTap = (item: { name: string; emoji: string; category: string }) => {
    addGroceryItem(item.name, item.category, "medium", item.emoji);
  };

  const startEditing = (item: GroceryItem) => {
    setEditingGroceryId(item.id);
    setEditName(item.name);
    setEditQuantity(item.quantity || "");
    setEditNotes(item.notes || "");
  };

  const saveEdit = (id: number) => {
    updateGroceryItem(id, { name: editName, quantity: editQuantity, notes: editNotes });
    setEditingGroceryId(null);
  };

  const filteredGrocery = activeCategory === "all" ? groceryItems : groceryItems.filter((i: any) => i.category === activeCategory);
  const categoryPresets = groceryPresets.filter(p => p.category === presetCategory);
  const visiblePresets = showAllPresets ? categoryPresets : categoryPresets.slice(0, PRESETS_PER_PAGE);

  // Progress stats
  const pickedUp = groceryItems.filter((i: any) => !i.needed).length;
  const totalItems = groceryItems.length;
  const pct = totalItems ? Math.round((pickedUp / totalItems) * 100) : 0;
  const autoAdded = groceryItems.filter((i: any) => i.autoGenerated || i.source === "recipe").length;

  const ringCircumference = 2 * Math.PI * 42;
  const ringStroke = (p: number) => `${(p / 100) * ringCircumference} ${ringCircumference}`;

  const clearCompleted = () => {
    groceryItems
      .filter((i: any) => !i.needed)
      .forEach((i: any) => deleteGroceryItem(i.id));
  };

  return (
    <div className="space-y-6 pb-6">
      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        {/* ── Left Column ────────────────────────────────── */}
        <div className="space-y-5">
          {/* ── Quick Add ── */}
          <div className="glass rounded-2xl p-4 sm:p-5">
            <p className="text-text-secondary text-xs font-semibold mb-3 flex items-center gap-1.5">
              <span>➕</span> Add Item
            </p>
            <div className="space-y-3">
              <div className="flex gap-2">
                <input
                  value={newGroceryItem}
                  onChange={e => setNewGroceryItem(e.target.value)}
                  onKeyDown={e => e.key === "Enter" && handleAdd()}
                  placeholder="What do you need?"
                  className="flex-1 min-w-0 rounded-2xl border border-[var(--color-surface-3)] bg-[var(--color-surface-0)]/50 px-4 py-2.5 text-sm font-semibold text-text-primary placeholder:text-text-muted/50 outline-none transition focus:border-[var(--color-accent-selected)]/50 focus:bg-[var(--color-surface-0)]/80 focus:ring-2 focus:ring-[var(--color-accent-selected)]/20"
                />
                <button
                  onClick={handleAdd}
                  disabled={!newGroceryItem.trim()}
                  className="cursor-pointer rounded-2xl bg-[var(--color-accent-button)] px-5 py-2.5 text-sm font-bold text-white shadow-lg shadow-[var(--color-accent-selected)]/25 transition hover:opacity-90 active:scale-95 disabled:opacity-40"
                >
                  Add
                </button>
              </div>
              <div className="flex gap-2">
                <select
                  value={newGroceryCategory}
                  onChange={e => setNewGroceryCategory(e.target.value)}
                  className="rounded-xl bg-[var(--color-surface-2)] text-text-secondary text-xs px-3 py-2 outline-none"
                >
                  {groceryCategories.map(cat => (
                    <option key={cat.id} value={cat.id}>{cat.emoji} {cat.name}</option>
                  ))}
                </select>
                <select
                  value={newGroceryPriority}
                  onChange={e => setNewGroceryPriority(e.target.value as "low" | "medium" | "high")}
                  className="rounded-xl bg-[var(--color-surface-2)] text-text-secondary text-xs px-3 py-2 outline-none"
                >
                  <option value="low">🟢 Low</option>
                  <option value="medium">🟡 Medium</option>
                  <option value="high">🔴 High</option>
                </select>
              </div>
            </div>

            {/* Recently Bought */}
            {recentlyBought && recentlyBought.length > 0 && (
              <div className="mt-4">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-[11px] font-semibold text-text-muted flex items-center gap-1">
                    <span>🕐</span> Recently Bought
                  </p>
                  <button
                    onClick={clearRecentlyBought}
                    className="text-[10px] text-text-muted hover:text-[var(--color-accent-rose)] transition-colors"
                  >
                    clear
                  </button>
                </div>
                <div className="flex gap-2 flex-wrap">
                  {recentlyBought.map((item: { name: string; emoji: string; category: string }) => (
                    <button
                      key={item.name}
                      onClick={() => handleRecentTap(item)}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-xs font-medium
                        bg-[var(--color-accent-amber)]/10 border border-[var(--color-accent-amber)]/20
                        text-[var(--color-accent-amber)] hover:bg-[var(--color-accent-amber)]/20
                        transition-all active:scale-95"
                    >
                      <span>{item.emoji}</span>
                      <span>{item.name}</span>
                      <span className="opacity-60">+</span>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Preset Chips */}
            <div className="mt-4">
              <p className="text-[11px] font-semibold text-text-muted mb-2 flex items-center gap-1">
                <span>⚡</span> Quick Add
              </p>
              <div className="flex gap-1.5 overflow-x-auto pb-1 -mx-1 px-1 mb-2 no-scrollbar">
                {groceryCategories.map(cat => (
                  <button
                    key={cat.id}
                    onClick={() => { setPresetCategory(cat.id); setShowAllPresets(false); }}
                    className={`shrink-0 flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-semibold transition-all ${
                      presetCategory === cat.id
                        ? "bg-[var(--color-accent-button)] text-white"
                        : "bg-[var(--color-surface-3)] text-text-secondary hover:text-text-primary"
                    }`}
                  >
                    {cat.emoji} {cat.name}
                  </button>
                ))}
              </div>
              <div className="flex gap-2 flex-wrap">
                {visiblePresets.map(preset => (
                  <button
                    key={preset.name}
                    onClick={() => handlePresetTap(preset)}
                    className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-xs font-medium
                      glass-subtle border border-[var(--color-surface-7)]/20
                      text-text-secondary hover:text-text-primary
                      hover:border-[var(--color-accent-selected)]/30 hover:bg-[var(--color-accent-selected)]/5
                      transition-all active:scale-95"
                  >
                    <span>{preset.emoji}</span>
                    <span>{preset.name}</span>
                    <span className="text-[var(--color-accent-selected)] opacity-70">+</span>
                  </button>
                ))}
              </div>
              {categoryPresets.length > PRESETS_PER_PAGE && (
                <button
                  onClick={() => setShowAllPresets(v => !v)}
                  className="mt-2 text-[11px] text-[var(--color-accent-selected)] hover:opacity-80 transition-opacity"
                >
                  {showAllPresets ? "Show less ↑" : `Show ${categoryPresets.length - PRESETS_PER_PAGE} more ↓`}
                </button>
              )}
            </div>
          </div>

          {/* ── Category Filter ── */}
          <div className="flex gap-2 overflow-x-auto pb-1 -mx-4 px-4 no-scrollbar">
            <button
              onClick={() => setActiveCategory("all")}
              className={`shrink-0 cursor-pointer rounded-full px-3.5 py-1.5 text-xs font-bold transition-all ${
                activeCategory === "all"
                  ? "bg-[var(--color-accent-selected)] text-white shadow-lg shadow-[var(--color-accent-selected)]/25"
                  : "glass-subtle text-text-secondary hover:text-text-primary"
              }`}
            >
              All
            </button>
            {groceryCategories.map(cat => {
              const catItems = groceryItems.filter((i: any) => i.category === cat.id);
              const catPicked = catItems.filter((i: any) => !i.needed).length;
              return (
                <button
                  key={cat.id}
                  onClick={() => setActiveCategory(cat.id)}
                  className={`shrink-0 cursor-pointer rounded-full px-3.5 py-1.5 text-xs font-bold transition-all flex items-center gap-1.5 ${
                    activeCategory === cat.id
                      ? "bg-[var(--color-accent-selected)] text-white shadow-lg shadow-[var(--color-accent-selected)]/25"
                      : "glass-subtle text-text-secondary hover:text-text-primary"
                  }`}
                >
                  <span>{cat.emoji}</span>
                  <span>{cat.name}</span>
                  {catItems.length > 0 && (
                    <span className={`text-[10px] ${activeCategory === cat.id ? "text-white/70" : "text-text-muted"}`}>
                      {catPicked}/{catItems.length}
                    </span>
                  )}
                </button>
              );
            })}
          </div>

          {/* ── Grocery Items by Category ── */}
          {groceryCategories.map(cat => {
            const catItems = filteredGrocery.filter((i: any) => i.category === cat.id);
            if (catItems.length === 0) return null;
            const catPicked = catItems.filter((i: any) => !i.needed).length;
            return (
              <section key={cat.id} className="liquid-glass rounded-2xl overflow-hidden">
                <div className="flex items-center justify-between px-4 pt-4 pb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-lg">{cat.emoji}</span>
                    <h3 className="text-sm font-bold text-text-primary">{cat.name}</h3>
                  </div>
                  <span className="glass-subtle rounded-full px-2.5 py-1 text-[11px] font-bold text-text-secondary">
                    {catPicked}/{catItems.length}
                  </span>
                </div>
                <div className="divide-y divide-[var(--color-surface-3)]">
                  {catItems.map((item: any, idx: number) => (
                    <div
                      key={`${cat.id}-${item.id}-${idx}`}
                      className={`group px-4 py-3 transition-all ${!item.needed ? "opacity-50" : ""}`}
                    >
                      {editingGroceryId === item.id ? (
                        <div className="space-y-2">
                          <div className="flex gap-2">
                            <input
                              value={editName}
                              onChange={e => setEditName(e.target.value)}
                              placeholder="Name"
                              className="flex-1 bg-transparent text-text-primary text-sm outline-none"
                              onKeyDown={e => e.key === "Enter" && saveEdit(item.id)}
                            />
                            <input
                              value={editQuantity}
                              onChange={e => setEditQuantity(e.target.value)}
                              placeholder="Qty"
                              className="w-16 bg-[var(--color-surface-2)] text-text-secondary text-xs rounded px-2 outline-none"
                            />
                          </div>
                          <input
                            value={editNotes}
                            onChange={e => setEditNotes(e.target.value)}
                            placeholder="Notes (optional)"
                            className="w-full bg-transparent text-text-secondary text-xs outline-none"
                          />
                          <div className="flex gap-2">
                            <button onClick={() => saveEdit(item.id)} className="px-3 py-1 rounded-lg bg-[var(--color-accent-button)] text-white text-xs font-medium cursor-pointer">Save</button>
                            <button onClick={() => setEditingGroceryId(null)} className="px-3 py-1 rounded-lg text-text-secondary text-xs cursor-pointer">Cancel</button>
                          </div>
                        </div>
                      ) : (
                        <div className="flex items-center gap-3">
                          {/* Checkbox — needed=true = empty (not picked up), needed=false = filled green (picked up) */}
                          <button
                            onClick={() => toggleGroceryNeeded(item.id)}
                            className={`flex h-7 w-7 shrink-0 cursor-pointer items-center justify-center rounded-lg border-2 transition-all active:scale-90 ${
                              !item.needed
                                ? "border-[var(--color-accent-mint)] bg-[var(--color-accent-mint)] text-white"
                                : "border-[var(--color-surface-4)] bg-[var(--color-surface-0)]/70 hover:border-[var(--color-accent-mint)]"
                            }`}
                          >
                            {!item.needed && (
                              <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3.5}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                              </svg>
                            )}
                          </button>
                          <span className="text-xl">{item.emoji}</span>
                          <div className="min-w-0 flex-1">
                            <p className={`text-sm font-semibold truncate ${!item.needed ? "text-text-muted line-through" : "text-text-primary"}`}>
                              {item.name}
                            </p>
                            {item.quantity && (
                              <p className="text-[11px] font-medium text-text-muted">{item.quantity}</p>
                            )}
                          </div>
                          <Badge variant={item.priority === "high" ? "rose" : item.priority === "medium" ? "amber" : "green"}>
                            {item.priority}
                          </Badge>
                          <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            <button
                              onClick={() => startEditing(item)}
                              className="cursor-pointer rounded-lg p-1.5 text-text-muted transition-colors hover:bg-[var(--color-surface-2)] hover:text-text-primary"
                            >
                              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-3.5 w-3.5">
                                <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7" strokeLinecap="round" strokeLinejoin="round" />
                                <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z" strokeLinecap="round" strokeLinejoin="round" />
                              </svg>
                            </button>
                            <button
                              onClick={() => deleteGroceryItem(item.id)}
                              className="cursor-pointer rounded-lg p-1.5 text-text-muted transition-colors hover:bg-[var(--color-accent-rose)]/10 hover:text-[var(--color-accent-rose)]"
                            >
                              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-3.5 w-3.5">
                                <path d="M3 6h18M19 6l-1 14H6L5 6M8 6V4h8v2" strokeLinecap="round" strokeLinejoin="round" />
                              </svg>
                            </button>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </section>
            );
          })}
        </div>

        {/* ── Right Column: Widgets ────────────────────── */}
        <div className="space-y-5 lg:order-2 order-first lg:order-none">
          {/* ── Shopping Progress ── */}
          <div className="glass rounded-2xl p-5">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold uppercase tracking-wider text-text-muted">
                Shopping progress
              </h3>
              <span className="text-2xl">🛒</span>
            </div>
            <div className="mt-3 flex items-end justify-between">
              <span className="text-4xl font-black text-text-primary">{pct}%</span>
              <span className="text-xs font-bold text-text-muted">
                {pickedUp} of {totalItems} picked up
              </span>
            </div>
            <div className="mt-3 h-3 overflow-hidden rounded-full bg-[var(--color-surface-2)]">
              <div
                className="h-full rounded-full transition-all duration-500"
                style={{
                  width: `${pct}%`,
                  background: `linear-gradient(90deg, var(--color-accent-mint, #34d399), var(--color-accent-amber, #fbbf24))`,
                }}
              />
            </div>
            {pickedUp > 0 && (
              <button
                onClick={clearCompleted}
                className="mt-4 w-full cursor-pointer rounded-2xl bg-[var(--color-surface-0)]/60 py-2.5 text-xs font-bold text-emerald-800/70 transition hover:bg-[var(--color-surface-0)]/80"
              >
                ✨ Clear {pickedUp} checked item{pickedUp > 1 ? "s" : ""}
              </button>
            )}
          </div>

          {/* ── Sync Buttons ── */}
          <div className="space-y-2">
            <button
              onClick={syncMealToGrocery}
              disabled={isSyncing}
              className="w-full flex items-center justify-center gap-1.5 py-2.5 rounded-2xl bg-[var(--color-accent-selected)]/10 text-[var(--color-accent-selected)] text-xs font-bold border border-[var(--color-accent-selected)]/20 hover:bg-[var(--color-accent-selected)]/20 transition-all disabled:opacity-60 cursor-pointer"
            >
              🍽️ {isSyncing ? "Syncing..." : "Sync from Meals"}
            </button>
            <button
              onClick={syncPantryToGrocery}
              disabled={isSyncing}
              className="w-full flex items-center justify-center gap-1.5 py-2.5 rounded-2xl glass text-text-secondary text-xs font-bold border border-[var(--color-surface-3)] hover:text-text-primary transition-all disabled:opacity-60 cursor-pointer"
            >
              🥫 Sync from Pantry
            </button>
          </div>

          {/* ── Auto-added notice ── */}
          {autoAdded > 0 && (
            <div className="glass-subtle rounded-2xl p-5" style={{ animation: "float 6s ease-in-out infinite" }}>
              <div className="flex items-start gap-3">
                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl text-2xl shadow" style={{ backgroundColor: `var(--color-accent-mint, #34d399)20` }}>
                  💚
                </div>
                <div>
                  <h4 className="font-bold text-text-primary">Auto-added from meals</h4>
                  <p className="mt-1 text-xs font-medium leading-relaxed text-text-secondary">
                    {autoAdded} item{autoAdded > 1 ? "s" : ""} were automatically added from this week&apos;s meal plan so you don&apos;t forget.
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* ── Mark All Needed ── */}
          <button
            onClick={() => {
              groceryItems
                .filter((i: any) => i.needed === false)
                .forEach((i: any) => toggleGroceryNeeded(i.id));
            }}
            className="w-full cursor-pointer rounded-2xl bg-[var(--color-surface-2)] py-2.5 text-xs font-medium text-text-secondary transition hover:bg-[var(--color-accent-selected)]/15 hover:text-[var(--color-accent-selected)]"
          >
            ☑️ Mark all as needed
          </button>
        </div>
      </div>
    </div>
  );
}