"use client";
import { useState, useMemo } from "react";
import Surface from "@/components/ui/Surface";
import SoftButton from "@/components/ui/SoftButton";
import Chip from "@/components/ui/Chip";
import TextField from "@/components/ui/TextField";
import ListRow from "@/components/ui/ListRow";
import SectionCard from "@/components/patterns/SectionCard";
import { groceryCategories, groceryPresets } from "@/data/meals";
import { GroceryItem } from "@/types/meals";

const PRESETS_PER_PAGE = 12;

export default function GroceryTab({
  groceryItems,
  setGroceryItems,
  activeCategory,
  setActiveCategory,
  isSyncing,
  recentlyBought,
  clearRecentlyBought,
  addGroceryItem,
  toggleGroceryNeeded,
  deleteGroceryItem,
  updateGroceryItem,
  syncMealToGrocery,
  syncPantryToGrocery,
  parseManualGroceryInput,
  guessCategory,
}: any) {
  const [newGroceryItem, setNewGroceryItem] = useState("");
  const [newGroceryQuantity, setNewGroceryQuantity] = useState("");
  const [newGroceryCategory, setNewGroceryCategory] = useState("auto");
  const [newGroceryPriority, setNewGroceryPriority] = useState<"low" | "medium" | "high">("medium");
  const [editingGroceryId, setEditingGroceryId] = useState<number | null>(null);
  const [editName, setEditName] = useState("");
  const [editQuantity, setEditQuantity] = useState("");
  const [editNotes, setEditNotes] = useState("");
  const [presetCategory, setPresetCategory] = useState<string>("produce");
  const [showAllPresets, setShowAllPresets] = useState(false);

  const handleAdd = async () => {
    if (!newGroceryItem.trim()) return;
    const parsed = parseManualGroceryInput(newGroceryItem);
    const category = newGroceryCategory === "auto" ? guessCategory(parsed.name) : newGroceryCategory;
    await addGroceryItem(parsed.name, category, newGroceryPriority, undefined, parsed.quantity || newGroceryQuantity, "");
    setNewGroceryItem("");
    setNewGroceryQuantity("");
  };

  const handlePresetTap = (preset: { name: string; emoji: string; category: string }) => {
    addGroceryItem(preset.name, preset.category, "medium", preset.emoji);
  };

  const handleRecentTap = (item: { name: string; emoji: string; category: string }) => {
    addGroceryItem(item.name, item.category, "medium", item.emoji);
  };

  const startEditing = (item: GroceryItem) => {
    setEditingGroceryId(item.id);
    setEditName(item.name);
    setEditQuantity(item.quantity || "");
    setEditNotes(item.notes || "");
  };

  const saveEdit = (id: number) => {
    updateGroceryItem(id, { name: editName.trim(), quantity: editQuantity.trim(), notes: editNotes.trim() });
    setEditingGroceryId(null);
  };

  const filteredGrocery = activeCategory === "all" ? groceryItems : groceryItems.filter((i: any) => i.category === activeCategory);
  const categoryPresets = groceryPresets.filter(p => p.category === presetCategory);
  const visiblePresets = showAllPresets ? categoryPresets : categoryPresets.slice(0, PRESETS_PER_PAGE);

  const pickedUp = groceryItems.filter((i: any) => !i.needed).length;
  const totalItems = groceryItems.length;
  const pct = totalItems ? Math.round((pickedUp / totalItems) * 100) : 0;
  const autoAdded = groceryItems.filter((i: any) => i.autoGenerated || i.source === "recipe").length;

  const clearCompleted = () => {
    groceryItems
      .filter((i: any) => !i.needed)
      .forEach((i: any) => deleteGroceryItem(i.id));
  };

  return (
    <div className="space-y-5 pb-6">
      <div className="grid gap-5 xl:grid-cols-[1fr_280px]">
        <div className="space-y-5">
          <SectionCard title="Add Item" icon="➕" description="Quick add items to your list">
            <div className="space-y-3">
              <div className="flex gap-2">
                <TextField
                  value={newGroceryItem}
                  onChange={e => setNewGroceryItem(e.target.value)}
                  onKeyDown={e => e.key === "Enter" && handleAdd()}
                  placeholder='e.g. "2 bananas" or just "milk"'
                  className="flex-1 min-w-0"
                />
                <SoftButton variant="primary" size="md" onClick={handleAdd} disabled={!newGroceryItem.trim()}>
                  Add
                </SoftButton>
              </div>
              <div className="flex gap-2">
                <TextField
                  value={newGroceryQuantity}
                  onChange={e => setNewGroceryQuantity(e.target.value)}
                  onKeyDown={e => e.key === "Enter" && handleAdd()}
                  placeholder="Qty"
                  className="w-20"
                />
                <div className="relative flex-1">
                  <select
                    value={newGroceryCategory}
                    onChange={e => setNewGroceryCategory(e.target.value)}
                    className="w-full h-11 rounded-2xl border border-white/10 bg-[var(--color-surface-2)] px-3 py-2.5 text-sm text-text-primary outline-none transition focus:border-[var(--color-accent-selected)]/50 focus:shadow-[0_0_0_4px_rgba(59,130,246,0.12)]"
                  >
                    <option value="auto">✨ Auto</option>
                    {groceryCategories.map(cat => (
                      <option key={cat.id} value={cat.id}>{cat.emoji} {cat.name}</option>
                    ))}
                  </select>
                </div>
                <div className="relative w-20">
                  <select
                    value={newGroceryPriority}
                    onChange={e => setNewGroceryPriority(e.target.value as "low" | "medium" | "high")}
                    className="w-full h-11 rounded-2xl border border-white/10 bg-[var(--color-surface-2)] px-3 py-2.5 text-sm text-text-primary outline-none transition focus:border-[var(--color-accent-selected)]/50 focus:shadow-[0_0_0_4px_rgba(59,130,246,0.12)]"
                  >
                    <option value="low">🟢 Low</option>
                    <option value="medium">🟡 Med</option>
                    <option value="high">🔴 High</option>
                  </select>
                </div>
              </div>
            </div>

            {recentlyBought && recentlyBought.length > 0 && (
              <div className="mt-4 pt-4 border-t border-white/10">
                <div className="flex items-center justify-between mb-2.5">
                  <p className="text-xs font-semibold uppercase tracking-wider text-text-secondary">
                    🕐 Recently Bought
                  </p>
                  <button
                    onClick={clearRecentlyBought}
                    className="text-[11px] text-text-muted hover:text-[var(--color-accent-rose)] transition-colors"
                  >
                    Clear
                  </button>
                </div>
                <div className="flex gap-2 flex-wrap">
                  {recentlyBought.map((item: { name: string; emoji: string; category: string }) => (
                    <Chip
                      key={item.name}
                      tone="neutral"
                      size="sm"
                      onClick={() => handleRecentTap(item)}
                      className="cursor-pointer"
                    >
                      {item.emoji} {item.name} +
                    </Chip>
                  ))}
                </div>
              </div>
            )}

            <div className="mt-4 pt-4 border-t border-white/10">
              <p className="text-xs font-semibold uppercase tracking-wider text-text-secondary mb-2.5">
                ⚡ Quick Add
              </p>
              <div className="flex gap-1.5 overflow-x-auto pb-1 -mx-1 px-1 mb-3">
                {groceryCategories.map(cat => (
                  <button
                    key={cat.id}
                    onClick={() => { setPresetCategory(cat.id); setShowAllPresets(false); }}
                    className={`shrink-0 rounded-full px-3 py-1.5 text-[11px] font-semibold transition-all duration-150 active:scale-95 ${
                      presetCategory === cat.id
                        ? "bg-[var(--color-accent-button)] text-white shadow-lg shadow-[var(--color-accent-selected)]/25"
                        : "border border-white/10 bg-[var(--color-surface-2)] text-text-secondary hover:text-text-primary hover:border-[var(--color-accent-selected)]/30"
                    }`}
                  >
                    {cat.emoji} {cat.name}
                  </button>
                ))}
              </div>
              <div className="flex gap-2 flex-wrap">
                {visiblePresets.map(preset => (
                  <Chip
                    key={preset.name}
                    tone="neutral"
                    size="sm"
                    onClick={() => handlePresetTap(preset)}
                    className="cursor-pointer hover:border-[var(--color-accent-selected)]/30"
                  >
                    {preset.emoji} {preset.name} <span className="text-[var(--color-accent-selected)] opacity-70">+</span>
                  </Chip>
                ))}
              </div>
              {categoryPresets.length > PRESETS_PER_PAGE && (
                <button
                  onClick={() => setShowAllPresets(v => !v)}
                  className="mt-2 text-[11px] text-[var(--color-accent-selected)] hover:opacity-80 transition-opacity"
                >
                  {showAllPresets ? "Show less ↑" : `Show ${categoryPresets.length - PRESETS_PER_PAGE} more ↓`}
                </button>
              )}
            </div>
          </SectionCard>

          <div className="flex gap-2 overflow-x-auto pb-1 -mx-4 px-4 no-scrollbar">
            <Chip
              tone={activeCategory === "all" ? "accent" : "neutral"}
              size="md"
              selected={activeCategory === "all"}
              onClick={() => setActiveCategory("all")}
            >
              All
            </Chip>
            {groceryCategories.map(cat => {
              const catItems = groceryItems.filter((i: any) => i.category === cat.id);
              const catPicked = catItems.filter((i: any) => !i.needed).length;
              return (
                <Chip
                  key={cat.id}
                  tone={activeCategory === cat.id ? "accent" : "neutral"}
                  size="md"
                  selected={activeCategory === cat.id}
                  onClick={() => setActiveCategory(cat.id)}
                >
                  {cat.emoji} {cat.name}
                  {catItems.length > 0 && (
                    <span className="opacity-60">{catPicked}/{catItems.length}</span>
                  )}
                </Chip>
              );
            })}
          </div>

          {groceryCategories.map(cat => {
            const catItems = filteredGrocery.filter((i: any) => i.category === cat.id);
            if (catItems.length === 0) return null;
            const catPicked = catItems.filter((i: any) => !i.needed).length;
            return (
              <SectionCard
                key={cat.id}
                title={cat.name}
                icon={cat.emoji}
                action={
                  <span className="text-xs font-semibold text-text-muted">
                    {catPicked}/{catItems.length}
                  </span>
                }
              >
                <div className="space-y-2">
                  {catItems.map((item: any, idx: number) => (
                    editingGroceryId === item.id ? (
                      <Surface key={`edit-${item.id}`} variant="warm" radius="2xl" padding="md">
                        <div className="space-y-2">
                          <div className="flex gap-2">
                            <TextField
                              value={editName}
                              onChange={e => setEditName(e.target.value)}
                              placeholder="Name"
                              onKeyDown={e => e.key === "Enter" && saveEdit(item.id)}
                              className="flex-1"
                            />
                            <TextField
                              value={editQuantity}
                              onChange={e => setEditQuantity(e.target.value)}
                              placeholder="Qty"
                              className="w-20"
                            />
                          </div>
                          <TextField
                            value={editNotes}
                            onChange={e => setEditNotes(e.target.value)}
                            placeholder="Notes (optional)"
                          />
                          <div className="flex gap-2">
                            <SoftButton variant="primary" size="sm" onClick={() => saveEdit(item.id)}>Save</SoftButton>
                            <SoftButton variant="ghost" size="sm" onClick={() => setEditingGroceryId(null)}>Cancel</SoftButton>
                          </div>
                        </div>
                      </Surface>
                    ) : (
                      <ListRow
                        key={`${cat.id}-${item.id}-${idx}`}
                        leading={
                          <button
                            onClick={() => toggleGroceryNeeded(item.id)}
                            className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-xl border-2 transition-all duration-150 active:scale-90 ${
                              !item.needed
                                ? "border-[var(--color-accent-mint)] bg-[var(--color-accent-mint)] text-white"
                                : "border-[var(--color-surface-4)] bg-[var(--color-surface-0)]/50 hover:border-[var(--color-accent-mint)]/50"
                            }`}
                          >
                            {!item.needed && (
                              <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3.5}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                              </svg>
                            )}
                          </button>
                        }
                        title={
                          <span className={!item.needed ? "line-through text-text-muted" : ""}>
                            {item.emoji} {item.name}
                          </span>
                        }
                        subtitle={item.quantity || undefined}
                        trailing={
                          <div className="flex items-center gap-2">
                            <Chip
                              tone={item.priority === "high" ? "danger" : item.priority === "medium" ? "warning" : "success"}
                              size="sm"
                            >
                              {item.priority}
                            </Chip>
                            <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                              <button
                                onClick={() => startEditing(item)}
                                className="rounded-xl p-1.5 text-text-muted transition-colors hover:bg-[var(--color-surface-2)] hover:text-text-primary"
                              >
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-3.5 w-3.5">
                                  <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7" strokeLinecap="round" strokeLinejoin="round" />
                                  <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                              </button>
                              <button
                                onClick={() => deleteGroceryItem(item.id)}
                                className="rounded-xl p-1.5 text-text-muted transition-colors hover:bg-[var(--color-accent-rose)]/10 hover:text-[var(--color-accent-rose)]"
                              >
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-3.5 w-3.5">
                                  <path d="M3 6h18M19 6l-1 14H6L5 6M8 6V4h8v2" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                              </button>
                            </div>
                          </div>
                        }
                        onClick={() => toggleGroceryNeeded(item.id)}
                      />
                    )
                  ))}
                </div>
              </SectionCard>
            );
          })}
        </div>

        <div className="space-y-5 xl:order-2 order-first xl:order-none">
          <SectionCard title="Shopping progress" icon="🛒">
            <div className="space-y-4">
              <div className="flex items-end justify-between">
                <span className="text-3xl font-black text-text-primary display-numeral">{pct}%</span>
                <span className="text-xs font-bold text-text-muted">
                  {pickedUp} of {totalItems} picked up
                </span>
              </div>
              <div className="h-3 overflow-hidden rounded-full bg-[var(--color-surface-2)]">
                <div
                  className="h-full rounded-full transition-all duration-500"
                  style={{
                    width: `${pct}%`,
                    background: `linear-gradient(90deg, var(--color-accent-mint, #34d399), var(--color-accent-amber, #fbbf24))`,
                  }}
                />
              </div>
              {pickedUp > 0 && (
                <SoftButton variant="ghost" size="md" onClick={clearCompleted} className="w-full text-emerald-400">
                  ✨ Clear {pickedUp} checked item{pickedUp > 1 ? "s" : ""}
                </SoftButton>
              )}
            </div>
          </SectionCard>

          <Surface variant="warm" radius="2xl" padding="none">
            <div className="space-y-2 p-5">
              <SoftButton variant="primary" size="md" onClick={syncMealToGrocery} disabled={isSyncing} className="w-full">
                🍽️ {isSyncing ? "Syncing..." : "Sync from Meals"}
              </SoftButton>
              <SoftButton variant="secondary" size="md" onClick={syncPantryToGrocery} disabled={isSyncing} className="w-full">
                🥫 Sync from Pantry
              </SoftButton>
            </div>
          </Surface>

          {autoAdded > 0 && (
            <SectionCard title="Auto-added from meals" icon="💚" description={`${autoAdded} item${autoAdded > 1 ? "s" : ""} were automatically added from this week's meal plan.`}>
              <p className="text-sm text-text-secondary">{autoAdded} item{autoAdded > 1 ? "s" : ""} from your meal plan added automatically.</p>
            </SectionCard>
          )}

          <SoftButton
            variant="ghost"
            size="md"
            onClick={() => {
              groceryItems
                .filter((i: any) => i.needed === false)
                .forEach((i: any) => toggleGroceryNeeded(i.id));
            }}
            className="w-full"
          >
            ☑️ Mark all as needed
          </SoftButton>
        </div>
      </div>
    </div>
  );
}