FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN npm install --production
COPY .next ./.next
COPY public ./public
COPY package.json ./package.json
COPY next.config.ts ./next.config.ts
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["npx", "next", "start"]
