import type { Meal, PantryItem, GroceryListItem } from './types';
import { db } from '@/db';

export interface SyncResult {
  added: number;
  updated: number;
  removed: number;
}

export class MealSyncService {
  async syncMealPlanToGrocery(userId: string): Promise<SyncResult> {
    try {
      const meals = await this.getScheduledMeals(userId);
      const pantryItems = await this.getPantryItems(userId);
      const existingGrocery = await this.getGroceryItemsBySource(userId, 'meal-plan');

      let added = 0;
      let updated = 0;

      for (const meal of meals) {
        const requiredIngredients = this.calculateRequiredIngredients(meal);

        for (const ingredient of requiredIngredients) {
          const pantryStock = this.findPantryStock(pantryItems, ingredient.name);
          const deficit = this.calculateDeficit(ingredient, pantryStock);

          if (deficit > 0) {
            const existing = existingGrocery.find(g =>
              g.name.toLowerCase() === ingredient.name.toLowerCase() && !g.manualOverride
            );

            if (existing) {
              await this.updateGroceryItem(existing.id, {
                quantity: `${deficit} ${ingredient.unit}`,
                lastSyncedAt: new Date().toISOString(),
              });
              updated++;
            } else {
              await this.createGroceryItem({
                userId,
                name: ingredient.name,
                category: ingredient.category,
                quantity: `${deficit} ${ingredient.unit}`,
                priority: 'medium',
                source: 'meal-plan',
                autoGenerated: true,
                manualOverride: false,
              });
              added++;
            }
          }
        }
      }

      return { added, updated, removed: 0 };
    } catch (e) {
      console.warn('[MealSync] syncMealPlanToGrocery failed', e);
      return { added: 0, updated: 0, removed: 0 };
    }
  }

  async syncPantryToGrocery(userId: string): Promise<SyncResult> {
    try {
      const pantryItems = await this.getPantryItems(userId);
      const allGrocery = (db as any).groceryStore || db.selectGrocery(userId);

      let added = 0;
      let updated = 0;

      // Iterate PANTRY items — add low/out items to grocery
      for (const pantry of pantryItems) {
        if (pantry.status === 'plenty') continue;

        const existing = allGrocery.find((g: any) =>
          g.name.toLowerCase() === pantry.name.toLowerCase() && !g.manualOverride
        );
        const priority = pantry.status === 'out' ? 'high' : 'medium';

        if (existing) {
          await this.updateGroceryItem(existing.id, {
            needed: true,
            priority,
            lastSyncedAt: new Date().toISOString(),
            source: 'pantry-check',
          });
          updated++;
        } else {
          await this.createGroceryItem({
            userId,
            name: pantry.name,
            category: this.getCategoryForIngredient(pantry.name),
            quantity: '1',
            priority,
            needed: true,
            source: 'pantry-check',
            autoGenerated: true,
            manualOverride: false,
          });
          added++;
        }
      }

      // Mark replenished pantry items as not needed in grocery
      for (const grocery of allGrocery) {
        if (grocery.manualOverride || !grocery.needed) continue;
        const pantryStock = this.findPantryStock(pantryItems, grocery.name);
        if (pantryStock && pantryStock.status === 'plenty') {
          await this.updateGroceryItem(grocery.id, {
            needed: false,
            lastSyncedAt: new Date().toISOString(),
          });
          updated++;
        }
      }

      return { added, updated, removed: 0 };
    } catch (e) {
      console.warn('[MealSync] syncPantryToGrocery failed', e);
      return { added: 0, updated: 0, removed: 0 };
    }
  }

  async toggleManualOverride(groceryId: number, override: boolean): Promise<void> {
    try {
      db.toggleGroceryOverride(groceryId, override);
    } catch (e) {
      console.warn('[MealSync] toggleManualOverride failed', e);
    }
  }

  private async getScheduledMeals(userId: string): Promise<Meal[]> {
    try {
      const fromDb = db.selectMeals(userId);
      if (fromDb && fromDb.length > 0) {
        return fromDb.map((m: any) => ({
          id: m.id ?? Date.now(),
          name: m.name,
          emoji: m.emoji ?? '🍽️',
          time: m.time ?? m.scheduledFor ?? 'Mon',
          prepTime: m.prepTime ?? '30 min',
          tags: typeof m.tags === 'string' ? (m.tags ? JSON.parse(m.tags) : []) : (m.tags ?? []),
          ingredients: typeof m.ingredients === 'string' ? (m.ingredients ? JSON.parse(m.ingredients) : []) : (m.ingredients ?? []),
          servings: m.servings ?? 4,
          calories: m.calories ?? 500,
          autoGenerated: m.autoGenerated,
        }));
      }
    } catch (e) {
      console.warn('[MealSync] db.selectMeals failed, using demo fallback', e);
    }

    return [
      { id: 1, name: "Pasta Primavera", emoji: "🍝", time: "Mon", prepTime: "25 min", tags: ["Vegetarian", "Quick"], ingredients: ["Penne pasta", "Zucchini", "Bell peppers", "Parmesan", "Olive oil"], servings: 4, calories: 420 },
      { id: 2, name: "Taco Night", emoji: "🌮", time: "Tue", prepTime: "20 min", tags: ["Family Fave", "Quick"], ingredients: ["Ground beef", "Taco shells", "Salsa", "Sour cream", "Lettuce", "Cheese"], servings: 4, calories: 550 },
      { id: 3, name: "Grilled Chicken", emoji: "🍗", time: "Wed", prepTime: "35 min", tags: ["High Protein", "Healthy"], ingredients: ["Chicken breast", "Broccoli", "Lemon", "Garlic", "Olive oil"], servings: 4, calories: 380 },
      { id: 4, name: "Shrimp Stir Fry", emoji: "🥢", time: "Thu", prepTime: "20 min", tags: ["Seafood", "Quick"], ingredients: ["Shrimp", "Snap peas", "Carrots", "Soy sauce", "Ginger", "Rice"], servings: 4, calories: 410 },
      { id: 5, name: "Homemade Pizza", emoji: "🍕", time: "Fri", prepTime: "45 min", tags: ["Family Fave", "Fun"], ingredients: ["Pizza dough", "Mozzarella", "Tomato sauce", "Bell peppers", "Mushrooms"], servings: 4, calories: 620 },
      { id: 6, name: "BBQ Ribs", emoji: "🍖", time: "Sat", prepTime: "2 hr", tags: ["Weekend", "Indulgent"], ingredients: ["Pork ribs", "BBQ sauce", "Corn on cob", "Coleslaw"], servings: 4, calories: 780 },
      { id: 7, name: "Slow Cooker Chili", emoji: "🫕", time: "Sun", prepTime: "6 hr", tags: ["Comfort Food", "Meal Prep"], ingredients: ["Ground beef", "Kidney beans", "Tomatoes", "Chili powder", "Onion"], servings: 6, calories: 490 },
    ];
  }

  private async getPantryItems(userId: string): Promise<PantryItem[]> {
    try {
      const items = db.selectPantry(userId);
      return items.map((p: any) => ({
        id: p.id ?? Date.now(),
        name: p.name,
        status: p.status ?? 'plenty',
      }));
    } catch (e) {
      console.warn('[MealSync] pantry fetch failed', e);
      return [];
    }
  }

  private async getGroceryItemsBySource(userId: string, source: string): Promise<GroceryListItem[]> {
    try {
      const all = db.selectGrocery(userId);
      return all
        .filter((g: any) =>
          g.source === source ||
          (source === 'meal-plan' && (g.autoGenerated || g.source === 'meal-plan')) ||
          g.autoGenerated
        )
        .map((g: any) => ({
          id: g.id,
          userId: g.userId || userId,
          name: g.name,
          category: g.category || 'other',
          aisle: g.aisle,
          quantity: g.quantity,
          notes: g.notes,
          priority: g.priority || 'medium',
          needed: g.needed !== false,
          source: g.source,
          autoGenerated: g.autoGenerated,
          manualOverride: g.manualOverride,
          lastSyncedAt: g.lastSyncedAt,
          updatedAt: g.updatedAt,
        }));
    } catch (e) {
      console.warn('[MealSync] grocery fetch failed', e);
      return [];
    }
  }

  private async createGroceryItem(data: Partial<GroceryListItem>): Promise<GroceryListItem> {
    const toUpsert = {
      userId: data.userId || 'demo',
      name: data.name || 'Unknown item',
      category: data.category || 'other',
      aisle: data.aisle || '1',
      quantity: data.quantity,
      notes: data.notes,
      priority: data.priority || 'medium',
      needed: data.needed !== false,
      source: data.source || 'meal-plan',
      autoGenerated: data.autoGenerated !== false,
      manualOverride: !!data.manualOverride,
      lastSyncedAt: data.lastSyncedAt,
    };
    const saved = db.upsertGroceryItem(toUpsert);
    return {
      id: saved.id,
      userId: saved.userId,
      name: saved.name,
      category: saved.category,
      aisle: saved.aisle,
      quantity: saved.quantity,
      notes: saved.notes,
      priority: saved.priority,
      needed: saved.needed,
      source: saved.source,
      autoGenerated: saved.autoGenerated,
      manualOverride: saved.manualOverride,
      lastSyncedAt: saved.lastSyncedAt,
      updatedAt: saved.updatedAt,
    } as GroceryListItem;
  }

  private async updateGroceryItem(id: number, updates: Partial<GroceryListItem>): Promise<void> {
    try {
      const gStore: any[] = (db as any).groceryStore || [];
      const idx = gStore.findIndex((g: any) => g.id === id);
      if (idx !== -1) {
        gStore[idx] = { ...gStore[idx], ...updates, updatedAt: new Date().toISOString() };
        return;
      }
      const merged = { id, ...updates, userId: 'demo' };
      db.upsertGroceryItem(merged);
    } catch (e) {
      console.warn('[MealSync] update failed for id', id, e);
    }
  }

  private getCategoryForIngredient(name: string): string {
    const n = name.toLowerCase();
    if (n.includes('pasta') || n.includes('rice') || n.includes('bean') || n.includes('oil') || n.includes('sauce') || n.includes('flour') || n.includes('sugar') || n.includes('shell') || n.includes('dough')) return 'pantry';
    if (n.includes('chicken') || n.includes('beef') || n.includes('pork') || n.includes('shrimp') || n.includes('salmon') || n.includes('fish') || n.includes('rib') || n.includes('meat')) return 'meat';
    if (n.includes('zucchini') || n.includes('pepper') || n.includes('broccoli') || n.includes('carrot') || n.includes('onion') || n.includes('tomato') || n.includes('lettuce') || n.includes('spinach') || n.includes('pea') || n.includes('corn') || n.includes('mushroom') || n.includes('avocado') || n.includes('garlic') || n.includes('lemon')) return 'produce';
    if (n.includes('milk') || n.includes('cheese') || n.includes('egg') || n.includes('yogurt') || n.includes('butter') || n.includes('parmesan') || n.includes('mozzarella') || n.includes('cheddar') || n.includes('sour cream')) return 'dairy';
    if (n.includes('frozen')) return 'frozen';
    if (n.includes('chip') || n.includes('snack') || n.includes('cereal') || n.includes('chili')) return 'snacks';
    if (n.includes('coffee') || n.includes('juice') || n.includes('soda') || n.includes('water')) return 'beverages';
    return 'other';
  }

  private guessUnitForIngredient(name: string): string {
    const n = name.toLowerCase();
    if (n.includes('oil') || n.includes('sauce') || n.includes('lemon')) return 'tbsp';
    if (n.includes('pasta') || n.includes('rice') || n.includes('bean')) return 'cup';
    if (n.includes('pepper') || n.includes('onion') || n.includes('tomato') || n.includes('zucchini')) return 'whole';
    if (n.includes('chicken') || n.includes('beef')) return 'lb';
    return 'unit';
  }

  private calculateRequiredIngredients(meal: Meal) {
    return meal.ingredients?.map(ing => ({
      name: ing,
      unit: this.guessUnitForIngredient(ing),
      category: this.getCategoryForIngredient(ing),
    })) || [];
  }

  private findPantryStock(pantry: PantryItem[], name: string) {
    return pantry.find(p => p.name.toLowerCase() === name.toLowerCase());
  }

  private calculateDeficit(ingredient: any, pantry: PantryItem | undefined): number {
    if (!pantry) return 2;
    if (pantry.status === 'out') return 3;
    if (pantry.status === 'low') return 1;
    return 0;
  }

  private parseQuantity(qty?: string): number {
    if (!qty) return 1;
    const match = qty.match(/(\d+(?:\.\d+)?)/);
    return match ? parseFloat(match[1]) : 1;
  }
}

export const mealSyncService = new MealSyncService();
