import type { Meal, PantryItem, GroceryListItem } from './types';
import { db } from '@/db';

export interface SyncResult {
  added: number;
  updated: number;
  removed: number;
}

interface RequiredIngredient {
  name: string;
  unit: string;
  category: string;
  quantity: number;
}

export class MealSyncService {
  async syncMealPlanToGrocery(userId: string, plannedMeals?: Meal[]): Promise<SyncResult> {
    try {
      const meals = plannedMeals && plannedMeals.length > 0 ? plannedMeals : await this.getScheduledMeals(userId);
      const pantryItems = await this.getPantryItems(userId);
      const existingGrocery = await this.getGroceryItemsBySource(userId, 'meal-plan');
      const requiredNames = new Set<string>();

      let added = 0;
      let updated = 0;
      let removed = 0;

      for (const meal of meals) {
        const requiredIngredients = this.calculateRequiredIngredients(meal);

        for (const ingredient of requiredIngredients) {
          requiredNames.add(this.normalizeIngredientName(ingredient.name));
          const pantryStock = this.findPantryStock(pantryItems, ingredient.name);
          const deficit = this.calculateDeficit(ingredient, pantryStock);

          if (deficit <= 0) continue;

          const existing = existingGrocery.find(g =>
            !g.manualOverride && !this.isManualSource(g.source) && this.ingredientNamesMatch(g.name, ingredient.name)
          );

          if (existing) {
            await this.updateGroceryItem(existing.id, {
              quantity: this.formatQuantity(deficit, ingredient.unit),
              priority: this.getPriorityForDeficit(deficit),
              needed: true,
              lastSyncedAt: new Date().toISOString(),
            });
            updated++;
          } else {
            await this.createGroceryItem({
              userId,
              name: ingredient.name,
              category: ingredient.category,
              aisle: this.getAisleForCategory(ingredient.category),
              quantity: this.formatQuantity(deficit, ingredient.unit),
              priority: this.getPriorityForDeficit(deficit),
              source: 'meal-plan',
              autoGenerated: true,
              manualOverride: false,
            });
            added++;
          }
        }
      }

      for (const grocery of existingGrocery) {
        if (grocery.manualOverride || this.isManualSource(grocery.source)) continue;
        if (this.shouldKeepMealPlanGrocery(grocery, requiredNames)) continue;
        await this.updateGroceryItem(grocery.id, {
          needed: false,
          lastSyncedAt: new Date().toISOString(),
        });
        removed++;
      }

      return { added, updated, removed };
    } catch (e) {
      console.warn('[MealSync] syncMealPlanToGrocery failed', e);
      return { added: 0, updated: 0, removed: 0 };
    }
  }

  async syncPantryToGrocery(userId: string): Promise<SyncResult> {
    try {
      const pantryItems = await this.getPantryItems(userId);
      const allGrocery = await this.getGroceryItemsBySource(userId, 'all');

      let added = 0;
      let updated = 0;

      for (const pantry of pantryItems) {
        if (pantry.status === 'plenty') continue;

        const existing = allGrocery.find((g: any) =>
          !g.manualOverride && !this.isManualSource(g.source) && this.ingredientNamesMatch(g.name, pantry.name)
        );
        const priority = pantry.status === 'out' ? 'high' : 'medium';

        if (existing) {
          await this.updateGroceryItem(existing.id, {
            needed: true,
            priority,
            lastSyncedAt: new Date().toISOString(),
            source: 'pantry-check',
          });
          updated++;
        } else {
          await this.createGroceryItem({
            userId,
            name: pantry.name,
            category: this.getCategoryForIngredient(pantry.name),
            aisle: this.getAisleForCategory(this.getCategoryForIngredient(pantry.name)),
            quantity: '1',
            priority,
            needed: true,
            source: 'pantry-check',
            autoGenerated: true,
            manualOverride: false,
          });
          added++;
        }
      }

      for (const grocery of allGrocery) {
        if (grocery.manualOverride || this.isManualSource(grocery.source) || !grocery.needed) continue;
        const pantryStock = this.findPantryStock(pantryItems, grocery.name);
        if (pantryStock && pantryStock.status === 'plenty') {
          await this.updateGroceryItem(grocery.id, {
            needed: false,
            lastSyncedAt: new Date().toISOString(),
          });
          updated++;
        }
      }

      return { added, updated, removed: 0 };
    } catch (e) {
      console.warn('[MealSync] syncPantryToGrocery failed', e);
      return { added: 0, updated: 0, removed: 0 };
    }
  }

  async toggleManualOverride(groceryId: number, override: boolean): Promise<void> {
    try {
      await db.toggleGroceryOverride(groceryId, override);
    } catch (e) {
      console.warn('[MealSync] toggleManualOverride failed', e);
    }
  }

  private async getScheduledMeals(userId: string): Promise<Meal[]> {
    try {
      const fromDb = db.selectMeals();
      if (fromDb && fromDb.length > 0) {
        return fromDb.map((m: any) => this.normalizeMeal(m));
      }

      const fromLocal = this.loadLocalMeals();
      if (fromLocal.length > 0) return fromLocal;
    } catch (e) {
      console.warn('[MealSync] db.selectMeals failed, using demo fallback', e);
    }

    return [
      { id: 1, name: "Pasta Primavera", emoji: "🍝", time: "Mon", mealType: "dinner", prepTime: "25 min", tags: ["Vegetarian", "Quick"], ingredients: ["Penne pasta", "Zucchini", "Bell peppers", "Parmesan", "Olive oil"], servings: 4, calories: 420 },
      { id: 2, name: "Taco Night", emoji: "🌮", time: "Tue", mealType: "dinner", prepTime: "20 min", tags: ["Family Fave", "Quick"], ingredients: ["Ground beef", "Taco shells", "Salsa", "Sour cream", "Lettuce", "Cheese"], servings: 4, calories: 550 },
      { id: 3, name: "Grilled Chicken", emoji: "🍗", time: "Wed", mealType: "dinner", prepTime: "35 min", tags: ["High Protein", "Healthy"], ingredients: ["Chicken breast", "Broccoli", "Lemon", "Garlic", "Olive oil"], servings: 4, calories: 380 },
      { id: 4, name: "Shrimp Stir Fry", emoji: "🥢", time: "Thu", mealType: "dinner", prepTime: "20 min", tags: ["Seafood", "Quick"], ingredients: ["Shrimp", "Snap peas", "Carrots", "Soy sauce", "Ginger", "Rice"], servings: 4, calories: 410 },
      { id: 5, name: "Homemade Pizza", emoji: "🍕", time: "Fri", mealType: "dinner", prepTime: "45 min", tags: ["Family Fave", "Fun"], ingredients: ["Pizza dough", "Mozzarella", "Tomato sauce", "Bell peppers", "Mushrooms"], servings: 4, calories: 620 },
      { id: 6, name: "BBQ Ribs", emoji: "🍖", time: "Sat", mealType: "dinner", prepTime: "2 hr", tags: ["Weekend", "Indulgent"], ingredients: ["Pork ribs", "BBQ sauce", "Corn on cob", "Coleslaw"], servings: 4, calories: 780 },
      { id: 7, name: "Slow Cooker Chili", emoji: "🫕", time: "Sun", mealType: "dinner", prepTime: "6 hr", tags: ["Comfort Food", "Meal Prep"], ingredients: ["Ground beef", "Kidney beans", "Tomatoes", "Chili powder", "Onion"], servings: 6, calories: 490 },
    ];
  }

  private async getPantryItems(userId: string): Promise<PantryItem[]> {
    try {
      const items = db.selectPantry();
      return items.map((p: any) => ({
        id: p.id ?? Date.now(),
        name: p.name || p.item,
        status: p.status ?? 'plenty',
      })).filter((p: PantryItem) => p.name);
    } catch (e) {
      console.warn('[MealSync] pantry fetch failed', e);
      return [];
    }
  }

  private async getGroceryItemsBySource(userId: string, source: string): Promise<GroceryListItem[]> {
    try {
      const all = db.selectGrocery();
      return all
        .filter((g: any) => source === 'all' || g.source === source || (source === 'meal-plan' && (g.autoGenerated || g.source === 'meal-plan')))
        .map((g: any) => ({
          id: g.id,
          userId: g.userId || userId,
          name: g.name,
          category: g.category || 'other',
          aisle: g.aisle,
          quantity: g.quantity,
          notes: g.notes,
          priority: g.priority || 'medium',
          needed: g.needed !== false,
          source: g.source,
          autoGenerated: g.autoGenerated,
          manualOverride: g.manualOverride,
          lastSyncedAt: g.lastSyncedAt,
          updatedAt: g.updatedAt,
        }));
    } catch (e) {
      console.warn('[MealSync] grocery fetch failed', e);
      return [];
    }
  }

  private async createGroceryItem(data: Partial<GroceryListItem>): Promise<GroceryListItem> {
    const category = data.category || 'other';
    const toUpsert = {
      userId: data.userId || 'demo',
      name: data.name || 'Unknown item',
      category,
      aisle: data.aisle || this.getAisleForCategory(category),
      quantity: data.quantity,
      notes: data.notes,
      priority: data.priority || 'medium',
      needed: data.needed !== false,
      source: data.source || 'meal-plan',
      autoGenerated: data.autoGenerated !== false,
      manualOverride: !!data.manualOverride,
      lastSyncedAt: data.lastSyncedAt,
    };
    const saved = await db.upsertGroceryItem(toUpsert);
    return {
      id: saved.id,
      userId: saved.userId,
      name: saved.name,
      category: saved.category,
      aisle: saved.aisle,
      quantity: saved.quantity,
      notes: saved.notes,
      priority: saved.priority,
      needed: saved.needed,
      source: saved.source,
      autoGenerated: saved.autoGenerated,
      manualOverride: saved.manualOverride,
      lastSyncedAt: saved.lastSyncedAt,
      updatedAt: saved.updatedAt,
    } as GroceryListItem;
  }

  private async updateGroceryItem(id: number, updates: Partial<GroceryListItem>): Promise<void> {
    try {
      const gStore: any[] = (db as any).groceryStore || [];
      const idx = gStore.findIndex((g: any) => g.id === id);
      if (idx !== -1) {
        gStore[idx] = { ...gStore[idx], ...updates, updatedAt: new Date().toISOString() };
        return;
      }
      const merged = { id, ...updates, userId: 'demo' };
      await db.upsertGroceryItem(merged);
    } catch (e) {
      console.warn('[MealSync] update failed for id', id, e);
    }
  }

  private normalizeMeal(meal: any): Meal {
    return {
      id: meal.id ?? Date.now(),
      name: meal.name,
      emoji: meal.emoji ?? '🍽️',
      time: meal.time ?? meal.scheduledFor ?? 'Mon',
      mealType: meal.mealType ?? 'dinner',
      prepTime: meal.prepTime ?? '30 min',
      tags: typeof meal.tags === 'string' ? (meal.tags ? JSON.parse(meal.tags) : []) : (meal.tags ?? []),
      ingredients: Array.isArray(meal.ingredients) ? meal.ingredients : (typeof meal.ingredients === 'string' ? (meal.ingredients ? JSON.parse(meal.ingredients) : []) : []),
      servings: meal.servings ?? 4,
      calories: meal.calories ?? 500,
      protein: meal.protein ?? 0,
      carbs: meal.carbs ?? 0,
      fat: meal.fat ?? 0,
      instructions: meal.instructions ?? '',
      autoGenerated: meal.autoGenerated,
    };
  }

  private loadLocalMeals(): Meal[] {
    if (typeof window === 'undefined') return [];
    try {
      const raw = localStorage.getItem('consuela-meals');
      if (!raw) return [];
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed.map((m: any) => this.normalizeMeal(m)) : [];
    } catch {
      return [];
    }
  }

  private shouldKeepMealPlanGrocery(grocery: GroceryListItem, requiredNames: Set<string>): boolean {
    const normalized = this.normalizeIngredientName(grocery.name);
    return requiredNames.has(normalized) || this.normalizeIngredientName(grocery.name).length === 0;
  }

  private getCategoryForIngredient(name: string): string {
    const n = name.toLowerCase();
    if (n.includes('pasta') || n.includes('rice') || n.includes('bean') || n.includes('oil') || n.includes('sauce') || n.includes('flour') || n.includes('sugar') || n.includes('shell') || n.includes('dough') || n.includes('salsa')) return 'pantry';
    if (n.includes('chicken') || n.includes('beef') || n.includes('pork') || n.includes('shrimp') || n.includes('salmon') || n.includes('fish') || n.includes('rib') || n.includes('meat') || n.includes('bacon')) return 'meat';
    if (n.includes('zucchini') || n.includes('pepper') || n.includes('broccoli') || n.includes('carrot') || n.includes('onion') || n.includes('tomato') || n.includes('lettuce') || n.includes('spinach') || n.includes('pea') || n.includes('corn') || n.includes('mushroom') || n.includes('avocado') || n.includes('garlic') || n.includes('lemon') || n.includes('banana') || n.includes('apple')) return 'produce';
    if (n.includes('milk') || n.includes('cheese') || n.includes('egg') || n.includes('yogurt') || n.includes('butter') || n.includes('parmesan') || n.includes('mozzarella') || n.includes('cheddar') || n.includes('sour cream')) return 'dairy';
    if (n.includes('frozen')) return 'frozen';
    if (n.includes('chip') || n.includes('snack') || n.includes('cereal') || n.includes('chili')) return 'snacks';
    if (n.includes('coffee') || n.includes('juice') || n.includes('soda') || n.includes('water')) return 'beverages';
    if (n.includes('soap') || n.includes('cleaner') || n.includes('tissue') || n.includes('paper towel') || n.includes('detergent')) return 'household';
    return 'other';
  }

  private getAisleForCategory(category: string): string {
    const map: Record<string, string> = {
      produce: '1',
      dairy: '4',
      meat: '6',
      pantry: '8',
      frozen: '11',
      snacks: '12',
      beverages: '13',
      household: '14',
    };
    return map[category] || '1';
  }

  private guessUnitForIngredient(name: string): string {
    const n = name.toLowerCase();
    if (n.includes('oil') || n.includes('sauce') || n.includes('lemon')) return 'tbsp';
    if (n.includes('pasta') || n.includes('rice') || n.includes('bean')) return 'cup';
    if (n.includes('pepper') || n.includes('onion') || n.includes('tomato') || n.includes('zucchini')) return 'whole';
    if (n.includes('chicken') || n.includes('beef') || n.includes('pork')) return 'lb';
    return 'unit';
  }

  private calculateRequiredIngredients(meal: Meal): RequiredIngredient[] {
    return (meal.ingredients || [])
      .map(ingredient => this.parseIngredient(ingredient))
      .filter(ingredient => ingredient.name);
  }

  private parseIngredient(raw: string): RequiredIngredient {
    const cleaned = String(raw || '')
      .replace(/[()[\]]/g, '')
      .replace(/\s+/g, ' ')
      .trim();

    if (!cleaned) {
      return { name: '', unit: 'unit', category: 'other', quantity: 0 };
    }

    const measured = cleaned.match(/^(\d+(?:\.\d+)?|\d+\/\d+)\s*(cups?|tbsp|tablespoons?|tsp|teaspoons?|oz|ounces?|lb|lbs|pounds?|g|grams?|kg|kilograms?|ml|l|liters?|cloves?|slices?|cans?|packages?|stalks?)\s+(.+)$/i);
    if (measured) {
      const name = measured[3].trim();
      return {
        name,
        unit: measured[2].toLowerCase(),
        category: this.getCategoryForIngredient(name),
        quantity: this.parseQuantity(measured[1]),
      };
    }

    const simple = cleaned.match(/^(\d+(?:\.\d+)?|\d+\/\d+)\s+(.+)$/);
    if (simple) {
      const name = simple[2].trim();
      return {
        name,
        unit: 'unit',
        category: this.getCategoryForIngredient(name),
        quantity: this.parseQuantity(simple[1]),
      };
    }

    return {
      name: cleaned,
      unit: this.guessUnitForIngredient(cleaned),
      category: this.getCategoryForIngredient(cleaned),
      quantity: 1,
    };
  }

  private parseQuantity(qty?: string | number): number {
    if (typeof qty === 'number') return Number.isFinite(qty) && qty > 0 ? qty : 1;
    if (!qty) return 1;
    const fraction = String(qty).match(/^(\d+)\/(\d+)$/);
    if (fraction) {
      const value = Number(fraction[1]) / Number(fraction[2]);
      return Number.isFinite(value) && value > 0 ? value : 1;
    }
    const match = String(qty).match(/(\d+(?:\.\d+)?)/);
    return match ? parseFloat(match[1]) : 1;
  }

  private findPantryStock(pantry: PantryItem[], name: string) {
    return pantry.find(p => this.ingredientNamesMatch(p.name || '', name));
  }

  private calculateDeficit(_ingredient: RequiredIngredient, pantry: PantryItem | undefined): number {
    if (!pantry) return 2;
    if (pantry.status === 'out') return 3;
    if (pantry.status === 'low') return 1;
    return 0;
  }

  private formatQuantity(quantity: number, unit: string): string {
    const safeQuantity = Math.max(1, Math.round(quantity));
    return unit === 'unit' ? `${safeQuantity}` : `${safeQuantity} ${unit}`;
  }

  private getPriorityForDeficit(quantity: number): 'low' | 'medium' | 'high' {
    if (quantity >= 3) return 'high';
    if (quantity >= 2) return 'medium';
    return 'low';
  }

  private normalizeIngredientName(name: string): string {
    return String(name || '')
      .toLowerCase()
      .replace(/&/g, ' and ')
      .replace(/[^\w\s]/g, ' ')
      .replace(/\b(the|fresh|diced|chopped|minced|sliced|canned|can of|package of|bag of)\b/g, ' ')
      .replace(/\b(\w+)s\b/g, '$1')
      .replace(/\s+/g, ' ')
      .trim();
  }

  private ingredientNamesMatch(left: string, right: string): boolean {
    const a = this.normalizeIngredientName(left);
    const b = this.normalizeIngredientName(right);
    if (!a || !b) return false;
    return a === b || (a.length > 3 && b.length > 3 && (a.includes(b) || b.includes(a)));
  }

  private isManualSource(source?: string): boolean {
    return source === 'manual';
  }
}

export const mealSyncService = new MealSyncService();
