export interface Meal {
  id: number;
  name: string;
  emoji: string;
  time: string;
  mealType?: "breakfast" | "lunch" | "dinner" | "snack";
  prepTime: string;
  tags: string[];
  ingredients: string[];
  servings: number;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  instructions?: string;
  autoGenerated?: boolean;
}

export interface PantryItem {
  id: number;
  name: string;
  status: "plenty" | "low" | "out";
}

export interface GroceryListItem {
  id: number;
  userId: string;
  name: string;
  category: string;
  aisle?: string;
  quantity?: string;
  notes?: string;
  priority: "low" | "medium" | "high";
  needed: boolean;
  source?: string;
  autoGenerated?: boolean;
  manualOverride?: boolean;
  lastSyncedAt?: string;
  updatedAt?: string;
}
