"use client";

import { useState, useRef, useEffect, useMemo } from "react";
import BottomNav from "@/components/ui/BottomNav";
import Avatar from "@/components/ui/Avatar";
import Badge from "@/components/ui/Badge";
import { db } from "@/db";

interface Message {
  id: number;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
  actions?: ActionCard[];
  speaker?: string;
  speakerEmoji?: string;
}

interface ActionCard {
  type: "event" | "meal" | "task" | "grocery";
  title: string;
  detail: string;
  emoji: string;
  confirmed?: boolean;
}

const CHAT_STORAGE_KEY = "consuela-chat-messages";
const SPEAKER_STORAGE_KEY = "consuela-chat-speaker";

function loadChatHistory(): Message[] {
  if (typeof window === "undefined") return [];
  try {
    const d = localStorage.getItem(CHAT_STORAGE_KEY);
    return d ? JSON.parse(d) : [];
  } catch { return []; }
}

function saveChatHistory(msgs: Message[]) {
  if (typeof window === "undefined") return;
  try { localStorage.setItem(CHAT_STORAGE_KEY, JSON.stringify(msgs)); } catch {}
}

const initialGreeting: Message = {
  id: 1,
  role: "assistant",
  content: "Hey there! 👋 I'm Consuela, your family assistant. I can help you manage your calendar, plan meals, organize tasks, and build grocery lists.\n\nJust tell me what you need!",
  timestamp: "Now",
};

const suggestedPrompts = [
  { label: "📅 Add event", prompt: "Add soccer practice tomorrow at 4pm for Caspian" },
  { label: "🍽️ Plan meals", prompt: "Plan dinners for this week" },
  { label: "✅ Assign chore", prompt: "Assign trash duty to Caspian every Thursday with 10 points" },
  { label: "🛒 Grocery list", prompt: "Generate grocery list for this week's meals" },
  { label: "📊 Family update", prompt: "What does the family have going on this week?" },
  { label: "🔔 Reminder", prompt: "Remind Dad about car service on Friday at 10am" },
];

const actionColors: Record<string, string> = {
  event: "border-violet-500/25 bg-violet-500/8",
  meal: "border-amber-500/25 bg-amber-500/8",
  task: "border-cyan-500/25 bg-cyan-500/8",
  grocery: "border-nori-500/25 bg-nori-500/8",
};

function renderContent(text: string) {
  return text.split("\n").map((line, i) => {
    const bold = line.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    return (
      <span key={i}>
        <span dangerouslySetInnerHTML={{ __html: bold }} />
        {i < text.split("\n").length - 1 && <br />}
      </span>
    );
  });
}

function executeAction(action: ActionCard): { success: boolean; message: string } {
  try {
    switch (action.type) {
      case "meal": {
        db.insertMeal({
          name: action.title, emoji: action.emoji || "🍽️", time: "Mon",
          prepTime: "30 min", tags: ["AI Suggested"], ingredients: [],
          servings: 4, calories: 500, userId: "demo",
        });
        return { success: true, message: `Added "${action.title}" to meals` };
      }
      case "task": {
        const TASKS_KEY = "consuela-tasks";
        const stored = (() => {
          if (typeof window === "undefined") return [];
          try { const d = localStorage.getItem(TASKS_KEY); return d ? JSON.parse(d) : []; } catch { return []; }
        })();
        const members = db.selectMembers();
        const assignee = action.detail?.match(/^(\w+)/)?.[1] || members[0]?.name || "Caspian";
        const member = members.find((m: any) => m.name === assignee || m.name.startsWith(assignee));
        const points = parseInt(action.detail?.match(/(\d+)\s*pts?/)?.[1] || "10");
        stored.push({
          id: Date.now(), title: action.title, assignee: member?.name || assignee,
          assigneeEmoji: member?.emoji || "🧒", due: "Today", points,
          recurring: null, category: "AI Suggested", completed: false, priority: "medium" as const,
        });
        if (typeof window !== "undefined") localStorage.setItem(TASKS_KEY, JSON.stringify(stored));
        return { success: true, message: `Created task "${action.title}" for ${member?.name || assignee} (${points}pts)` };
      }
      case "grocery": {
        db.upsertGroceryItem({
          name: action.title, category: "pantry", aisle: "1", quantity: "1",
          priority: "medium", needed: true, source: "ai", autoGenerated: false, userId: "demo",
        });
        return { success: true, message: `Added "${action.title}" to grocery list` };
      }
      case "event": {
        const EVENTS_KEY = "consuela-events";
        const stored = (() => {
          if (typeof window === "undefined") return [];
          try { const d = localStorage.getItem(EVENTS_KEY); return d ? JSON.parse(d) : []; } catch { return []; }
        })();
        stored.push({
          id: Date.now(), title: action.title, time: "4:00 PM",
          member: action.detail?.split("·")?.[0]?.trim() || "All",
          color: "green" as const, emoji: action.emoji || "📅", day: new Date().getDate(),
        });
        if (typeof window !== "undefined") localStorage.setItem(EVENTS_KEY, JSON.stringify(stored));
        return { success: true, message: `Added event "${action.title}"` };
      }
      default:
        return { success: false, message: `Unknown action type` };
    }
  } catch (err) {
    return { success: false, message: err instanceof Error ? err.message : "Failed" };
  }
}

export default function ChatPage() {
  const membersData = useMemo(() => db.selectMembers(), []);
  const memberOptions = useMemo(() =>
    membersData.filter((m: any) => m.role !== "pet").map((m: any) => ({
      name: m.name,
      emoji: m.emoji,
      color: m.color,
    })), [membersData]);

  // Load saved speaker or default to first member
  const [currentSpeaker, setCurrentSpeaker] = useState<{ name: string; emoji: string; color: string }>(() => {
    if (typeof window === "undefined") return memberOptions[0] || { name: "Mom", emoji: "👩", color: "green" };
    try {
      const saved = localStorage.getItem(SPEAKER_STORAGE_KEY);
      if (saved) return JSON.parse(saved);
    } catch {}
    return memberOptions[0] || { name: "Mom", emoji: "👩", color: "green" };
  });

  const saveSpeaker = (speaker: typeof currentSpeaker) => {
    setCurrentSpeaker(speaker);
    if (typeof window !== "undefined") {
      localStorage.setItem(SPEAKER_STORAGE_KEY, JSON.stringify(speaker));
    }
  };

  // Load persisted messages
  const [messages, setMessages] = useState<Message[]>(() => {
    const saved = loadChatHistory();
    return saved.length > 0 ? saved : [initialGreeting];
  });

  // Save messages on every change
  useEffect(() => {
    if (messages.length > 0) saveChatHistory(messages);
  }, [messages]);

  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(true);
  const [isListening, setIsListening] = useState(false);
  const [showSpeakerPicker, setShowSpeakerPicker] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const recognitionRef = useRef<any>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  useEffect(() => {
    if (typeof window !== "undefined" && ("webkitSpeechRecognition" in window || "SpeechRecognition" in window)) {
      const SpeechRecognition = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition;
      recognitionRef.current = new SpeechRecognition();
      recognitionRef.current.continuous = false;
      recognitionRef.current.interimResults = false;
      recognitionRef.current.lang = "en-US";
      recognitionRef.current.onresult = (event: any) => {
        setInput(event.results[0][0].transcript);
        setIsListening(false);
      };
      recognitionRef.current.onerror = () => setIsListening(false);
      recognitionRef.current.onend = () => setIsListening(false);
    }
    return () => { if (recognitionRef.current) recognitionRef.current.stop(); };
  }, []);

  const msgCounter = useRef(Math.max(100, ...messages.map(m => m.id)));

  const sendMessage = async (text: string) => {
    if (!text.trim()) return;

    msgCounter.current += 1;
    const userMsg: Message = {
      id: msgCounter.current,
      role: "user",
      content: text.trim(),
      timestamp: "Just now",
      speaker: currentSpeaker.name,
      speakerEmoji: currentSpeaker.emoji,
    };

    const updated = [...messages, userMsg];
    setMessages(updated);
    setInput("");
    setIsTyping(true);
    setShowSuggestions(false);

    try {
      const res = await fetch('/api/hermes/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: text,
          context: `Current speaker: ${currentSpeaker.name}. Family members: ${memberOptions.map(m => `${m.name} (${m.emoji})`).join(", ")}.`,
        }),
      });
      const aiResponse = await res.json();
      setIsTyping(false);

      const actions = aiResponse.actions || [];
      const executedActions = actions.map((action: ActionCard) => {
        const result = executeAction(action);
        return { ...action, confirmed: result.success };
      });

      const resultMsgs = executedActions
        .filter((a: ActionCard) => a.confirmed)
        .map((a: ActionCard) => `✅ ${a.title}`);
      const content = aiResponse.content || aiResponse.reply || "I processed that.";
      const fullContent = resultMsgs.length > 0 ? content + "\n\n" + resultMsgs.join("\n") : content;

      msgCounter.current += 1;
      const response: Message = {
        id: msgCounter.current,
        role: "assistant",
        content: fullContent,
        timestamp: "Just now",
        actions: executedActions,
      };
      setMessages(prev => [...prev, response]);
    } catch (error) {
      setIsTyping(false);
      msgCounter.current += 1;
      setMessages(prev => [...prev, {
        id: msgCounter.current,
        role: "assistant",
        content: "Sorry, I'm having trouble right now. Please try again.",
        timestamp: "Just now",
      }]);
    }
  };

  const clearChat = () => {
    setMessages([initialGreeting]);
    saveChatHistory([initialGreeting]);
  };

  const toggleListening = () => {
    if (!recognitionRef.current) return;
    isListening ? recognitionRef.current.stop() : recognitionRef.current.start();
    setIsListening(!isListening);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage(input);
    }
  };

  return (
    <div className="min-h-screen bg-surface-0 max-w-lg mx-auto flex flex-col">
      {/* Top bar */}
      <div
        className="sticky top-0 z-40 px-4 py-3 flex items-center gap-3 bg-surface-0/90 backdrop-blur-md border-b border-surface-3/20"
        style={{ paddingTop: "calc(env(safe-area-inset-top) + 0.75rem)" }}
      >
        <div className="w-10 h-10 rounded-xl flex items-center justify-center text-xl shrink-0 bg-nori-500/15 consuela-glow">
          ✨
        </div>
        <div className="flex-1 min-w-0">
          <h1 className="text-base font-semibold text-text-primary">Consuela</h1>
          <div className="flex items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-nori-400 animate-pulse" />
            <span className="text-xs text-text-secondary">AI Family Assistant</span>
          </div>
        </div>

        {/* Speaker selector */}
        <div className="relative">
          <button
            onClick={() => setShowSpeakerPicker(!showSpeakerPicker)}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl bg-surface-2 text-text-secondary hover:text-text-primary transition-colors text-xs"
          >
            <span>{currentSpeaker.emoji}</span>
            <span className="max-w-[60px] truncate">{currentSpeaker.name.split(" ")[0]}</span>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3 h-3">
              <path d="M6 9l6 6 6-6" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </button>
          {showSpeakerPicker && (
            <div className="absolute right-0 top-full mt-1 bg-surface-0 border border-surface-3 rounded-xl shadow-xl z-50 py-1 min-w-[160px]"
              onClick={() => setShowSpeakerPicker(false)}>
              {memberOptions.map(m => (
                <button
                  key={m.name}
                  onClick={() => saveSpeaker(m)}
                  className={`w-full flex items-center gap-2 px-3 py-2 text-xs hover:bg-surface-2 transition-colors ${
                    currentSpeaker.name === m.name ? "text-nori-400 bg-nori-500/10" : "text-text-primary"
                  }`}
                >
                  <span>{m.emoji}</span>
                  <span>{m.name}</span>
                  {currentSpeaker.name === m.name && <span className="ml-auto text-nori-400">✓</span>}
                </button>
              ))}
            </div>
          )}
        </div>

        <button onClick={clearChat} className="w-9 h-9 flex items-center justify-center rounded-xl bg-surface-2 text-text-secondary hover:text-text-primary transition-colors text-xs" title="Clear chat">
          🗑️
        </button>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex gap-2.5 ${msg.role === "user" ? "flex-row-reverse" : "flex-row"}`}
          >
            {msg.role === "assistant" && (
              <div className="w-8 h-8 rounded-xl bg-nori-500/15 flex items-center justify-center text-sm shrink-0 mt-0.5">✨</div>
            )}
            {msg.role === "user" && (
              <Avatar name={msg.speaker || currentSpeaker.name}
                color={currentSpeaker.color || "green"}
                emoji={msg.speakerEmoji || currentSpeaker.emoji}
                size="sm" variant="emoji" />
            )}
            <div className={`max-w-[82%] space-y-2 ${msg.role === "user" ? "items-end" : "items-start"} flex flex-col`}>
              {/* Speaker label */}
              {msg.role === "user" && msg.speaker && (
                <span className="text-[10px] text-text-muted px-1">{msg.speaker.split(" ")[0]}</span>
              )}
              <div
                className={`rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                  msg.role === "user"
                    ? "bg-nori-600 text-white rounded-tr-sm"
                    : "glass text-text-primary rounded-tl-sm"
                }`}
              >
                {renderContent(msg.content)}
              </div>

              {msg.actions?.map((action, i) => (
                <div key={i}
                  className={`rounded-xl px-3 py-2.5 flex items-center gap-2.5 border w-full max-w-xs ${actionColors[action.type]}`}>
                  <span className="text-xl shrink-0">{action.emoji}</span>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs font-semibold text-text-primary truncate">{action.title}</p>
                    <p className="text-[11px] text-text-secondary truncate">{action.detail}</p>
                  </div>
                  {action.confirmed && (
                    <div className="w-5 h-5 rounded-full bg-nori-500 flex items-center justify-center shrink-0">
                      <svg viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth={3} className="w-3 h-3">
                        <path d="M5 13l4 4L19 7" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                  )}
                </div>
              ))}

              <span className="text-[10px] text-text-muted px-1">{msg.timestamp}</span>
            </div>
          </div>
        ))}

        {isTyping && (
          <div className="flex gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-nori-500/15 flex items-center justify-center text-sm shrink-0">✨</div>
            <div className="glass rounded-2xl rounded-tl-sm px-4 py-3 flex items-center gap-1">
              {[0, 1, 2].map((i) => (
                <div key={i} className="w-2 h-2 rounded-full bg-nori-400"
                  style={{ animation: `bounce 1s ease-in-out ${i * 0.15}s infinite` }} />
              ))}
            </div>
          </div>
        )}

        {showSuggestions && messages.length <= 1 && (
          <div className="pt-2">
            <p className="text-text-muted text-xs mb-3 text-center">Try asking…</p>
            <div className="grid grid-cols-2 gap-2">
              {suggestedPrompts.map((s) => (
                <button key={s.label} onClick={() => sendMessage(s.prompt)}
                  className="glass rounded-xl px-3 py-2.5 text-left text-xs text-text-secondary hover:text-text-primary hover:border-nori-500/30 transition-all active:scale-95">
                  {s.label}
                </button>
              ))}
            </div>
          </div>
        )}

        <div ref={bottomRef} />
      </div>

      {/* Input area */}
      <div
        className="sticky bottom-0 px-4 pb-24 pt-3"
        style={{
          background: "linear-gradient(to top, var(--color-surface-0) 70%, transparent)",
          paddingBottom: "calc(env(safe-area-inset-bottom) + 5.5rem)",
        }}
      >
        <div className="flex items-end gap-2 rounded-2xl glass px-3 py-2 border border-accent-selected/15">
          <button onClick={toggleListening}
            className={`w-9 h-9 flex items-center justify-center rounded-xl transition-colors shrink-0 mb-0.5 ${
              isListening ? "text-red-400 bg-red-500/10" : "text-text-secondary hover:text-nori-400"}`}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="w-5 h-5">
              <path d="M12 1a3 3 0 00-3 3v8a3 3 0 006 0V4a3 3 0 00-3-3z" strokeLinecap="round" />
              <path d="M19 10v2a7 7 0 01-14 0v-2" strokeLinecap="round" />
              <line x1="12" y1="19" x2="12" y2="23" strokeLinecap="round" />
              <line x1="8" y1="23" x2="16" y2="23" strokeLinecap="round" />
            </svg>
          </button>

          <textarea
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={`Message Consuela as ${currentSpeaker.name.split(" ")[0]}…`}
            rows={1}
            className="flex-1 bg-transparent text-text-primary text-sm placeholder:text-text-muted resize-none outline-none leading-relaxed py-1.5 max-h-28"
            style={{ minHeight: "36px" }}
          />

          <button onClick={() => sendMessage(input)} disabled={!input.trim()}
            className={`w-9 h-9 flex items-center justify-center rounded-xl shrink-0 mb-0.5 transition-all ${
              input.trim() ? "bg-nori-500 text-white hover:bg-nori-400 active:scale-95" : "bg-surface-3 text-text-muted cursor-not-allowed"}`}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} className="w-4 h-4">
              <path d="M22 2L11 13" strokeLinecap="round" strokeLinejoin="round" />
              <path d="M22 2L15 22l-4-9-9-4 20-7z" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </button>
        </div>

        <div className="flex gap-2 mt-2.5 overflow-x-auto pb-0.5">
          <Badge variant="gray">📅 Calendar</Badge>
          <Badge variant="gray">🍽️ Meals</Badge>
          <Badge variant="gray">✅ Tasks</Badge>
          <Badge variant="gray">🛒 Grocery</Badge>
        </div>
      </div>

      <BottomNav />

      <style>{`
        @keyframes bounce {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-5px); }
        }
      `}</style>
    </div>
  );
}
