"use client";

import { useState, useEffect, useRef, Suspense } from "react";
import PageShell from "@/components/ui/PageShell";
import TopBar from "@/components/ui/TopBar";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import Link from "next/link";
import { db } from "@/db";
import { mealSyncService } from "@/services/mealSync";
import { useSearchParams } from "next/navigation";

interface Meal {
  id: number;
  name: string;
  emoji: string;
  time: string;
  mealType?: "breakfast" | "lunch" | "dinner" | "snack";
  prepTime: string;
  tags: string[];
  ingredients: string[];
  servings: number;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  instructions?: string;
  autoGenerated?: boolean;
}

interface Recipe {
  id: number;
  name: string;
  emoji: string;
  prepTime: string;
  cookTime?: string;
  tags: string[];
  ingredients: string[];
  instructions: string;
  servings: number;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  source?: string;
  createdAt: string;
}

interface PantryItem {
  id: number;
  item: string;
  status: "plenty" | "low" | "out";
}

interface GroceryItem {
  id: number;
  name: string;
  emoji: string;
  category: string;
  aisle: string;
  quantity?: string;
  notes?: string;
  priority: "low" | "medium" | "high";
  needed: boolean;
  manualOverride?: boolean;
  lastSyncedAt?: string;
  source?: string;
  autoGenerated?: boolean;
}

const defaultMeals: Meal[] = [
  { id: 1, name: "Cereal & Fruit", emoji: "🥣", time: "Mon", mealType: "breakfast", prepTime: "5 min", tags: ["Quick", "Kids"], ingredients: ["Cereal", "Milk", "Bananas"], servings: 4, calories: 320 },
  { id: 2, name: "Pasta Primavera", emoji: "🍝", time: "Mon", mealType: "dinner", prepTime: "25 min", tags: ["Vegetarian", "Quick"], ingredients: ["Penne pasta", "Zucchini", "Bell peppers", "Parmesan", "Olive oil"], servings: 4, calories: 420, protein: 14, carbs: 62, fat: 12 },
  { id: 3, name: "Taco Night", emoji: "🌮", time: "Tue", mealType: "dinner", prepTime: "20 min", tags: ["Family Fave", "Quick"], ingredients: ["Ground beef", "Taco shells", "Salsa", "Sour cream", "Lettuce", "Cheese"], servings: 4, calories: 550, protein: 28, carbs: 45, fat: 22 },
  { id: 4, name: "Grilled Chicken", emoji: "🍗", time: "Wed", mealType: "dinner", prepTime: "35 min", tags: ["High Protein", "Healthy"], ingredients: ["Chicken breast", "Broccoli", "Lemon", "Garlic", "Olive oil"], servings: 4, calories: 380, protein: 42, carbs: 18, fat: 14 },
  { id: 5, name: "Shrimp Stir Fry", emoji: "🥢", time: "Thu", mealType: "dinner", prepTime: "20 min", tags: ["Seafood", "Quick"], ingredients: ["Shrimp", "Snap peas", "Carrots", "Soy sauce", "Ginger", "Rice"], servings: 4, calories: 410, protein: 32, carbs: 48, fat: 8 },
  { id: 6, name: "Homemade Pizza", emoji: "🍕", time: "Fri", mealType: "dinner", prepTime: "45 min", tags: ["Family Fave", "Fun"], ingredients: ["Pizza dough", "Mozzarella", "Tomato sauce", "Bell peppers", "Mushrooms"], servings: 4, calories: 620, protein: 24, carbs: 78, fat: 22 },
  { id: 7, name: "BBQ Ribs", emoji: "🍖", time: "Sat", mealType: "dinner", prepTime: "2 hr", tags: ["Weekend", "Indulgent"], ingredients: ["Pork ribs", "BBQ sauce", "Corn on cob", "Coleslaw"], servings: 4, calories: 780, protein: 48, carbs: 42, fat: 38 },
  { id: 8, name: "Slow Cooker Chili", emoji: "🫕", time: "Sun", mealType: "dinner", prepTime: "6 hr", tags: ["Comfort Food", "Meal Prep"], ingredients: ["Ground beef", "Kidney beans", "Tomatoes", "Chili powder", "Onion"], servings: 6, calories: 490, protein: 34, carbs: 52, fat: 16 },
];

const mealIdeas = [
  { name: "Salmon & Asparagus", emoji: "🐟", tags: ["Healthy"] },
  { name: "Veggie Curry", emoji: "🍛", tags: ["Vegetarian"] },
  { name: "BLT Sandwiches", emoji: "🥪", tags: ["Quick"] },
  { name: "Mac & Cheese", emoji: "🧀", tags: ["Kids Love"] },
];

const weekDays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

const foodEmojis = [
  "🍕","🍝","🌮","🍗","🍖","🫕","🥢","🍛","🥩","🍳",
  "🥗","🥘","🍲","🍜","🍱","🥙","🫔","🌯","🥪","🧆",
  "🐟","🦞","🍣","🥐","🍞","🧁","🎂","🍰","🍩","🥞",
  "🫐","🍓","🍇","🍎","🥑","🥦","🥕","🌽","🍠","🧅",
];

const groceryCategories = [
  { id: "produce", name: "Produce", emoji: "🥬", aisles: ["1-3"] },
  { id: "dairy", name: "Dairy", emoji: "🥛", aisles: ["4-5"] },
  { id: "meat", name: "Meat & Seafood", emoji: "🥩", aisles: ["6-7"] },
  { id: "pantry", name: "Pantry", emoji: "🍝", aisles: ["8-10"] },
  { id: "frozen", name: "Frozen", emoji: "🧊", aisles: ["11"] },
  { id: "snacks", name: "Snacks", emoji: "🍿", aisles: ["12"] },
  { id: "beverages", name: "Beverages", emoji: "☕", aisles: ["13"] },
  { id: "household", name: "Household", emoji: "🧽", aisles: ["14-15"] },
];

const initialGroceryItems: GroceryItem[] = [
  { id: 1, name: "Bananas", emoji: "🍌", category: "produce", aisle: "1", priority: "medium", needed: true },
  { id: 2, name: "Baby spinach", emoji: "🥬", category: "produce", aisle: "2", priority: "high", needed: true },
  { id: 3, name: "Avocados", emoji: "🥑", category: "produce", aisle: "2", priority: "medium", needed: false },
  { id: 4, name: "Milk", emoji: "🥛", category: "dairy", aisle: "4", priority: "high", needed: true },
  { id: 5, name: "Eggs", emoji: "🥚", category: "dairy", aisle: "4", priority: "high", needed: true },
  { id: 6, name: "Cheddar cheese", emoji: "🧀", category: "dairy", aisle: "5", priority: "medium", needed: false },
  { id: 7, name: "Chicken breast", emoji: "🍗", category: "meat", aisle: "6", priority: "high", needed: true },
  { id: 8, name: "Ground beef", emoji: "🥩", category: "meat", aisle: "6", priority: "medium", needed: true },
  { id: 9, name: "Pasta", emoji: "🍝", category: "pantry", aisle: "8", priority: "medium", needed: true },
  { id: 10, name: "Olive oil", emoji: "🫒", category: "pantry", aisle: "8", priority: "low", needed: false },
  { id: 11, name: "Coffee", emoji: "☕", category: "beverages", aisle: "13", priority: "high", needed: true },
];

const RECIPE_TAGS = ["Vegetarian", "Vegan", "Quick", "Family Fave", "Healthy", "High Protein", "Seafood", "Weekend", "Comfort Food", "Meal Prep", "Gluten-Free", "Dairy-Free", "Indulgent", "Fun", "Kids Love"];

const emptyRecipe = {
  name: "",
  emoji: "🍳",
  time: "Mon",
  prepTime: "",
  servings: 4,
  calories: 0,
  protein: 0,
  carbs: 0,
  fat: 0,
  tags: [] as string[],
  ingredients: [""],
  instructions: "",
};

type Tab = "meals" | "grocery" | "pantry" | "recipes";

function MealHubContent() {
  const searchParams = useSearchParams();
  const initialTab = (searchParams.get("tab") as Tab) || "meals";
  const [activeTab, setActiveTab] = useState<Tab>(initialTab);
  const [activeDay, setActiveDay] = useState("Tue");
  const [showNutrition, setShowNutrition] = useState(false);
  const [meals, setMeals] = useState<Meal[]>([]);
  const [notification, setNotification] = useState<string | null>(null);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncStatus, setSyncStatus] = useState("");

  // Recipe Creator
  const [showRecipeModal, setShowRecipeModal] = useState(false);
  const [editingMealId, setEditingMealId] = useState<number | null>(null);
  const [recipe, setRecipe] = useState({ ...emptyRecipe });
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);

  // AI meal suggestions
  const [aiMealIdeas, setAiMealIdeas] = useState<Array<{ name: string; emoji: string; tags: string[] }>>([]);
  const [aiMealLoading, setAiMealLoading] = useState(false);
  const [showAiSuggestions, setShowAiSuggestions] = useState(false);

  const generateAiMeals = async () => {
    setAiMealLoading(true);
    setShowAiSuggestions(true);
    try {
      const pantry = db.selectPantry().map((p: any) => p.name).join(", ");
      const res = await fetch('/api/hermes/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `Suggest 4 meal ideas for a family of 7 (kids ages 5-14). Pantry has: ${pantry || "basic ingredients"}. Return as JSON: {"actions":[{"type":"meal","title":"Meal Name","detail":"Prep time · Kid-friendly tags","emoji":"🍝"}]}. Make them varied, practical, and family-friendly.`,
        }),
      });
      const data = await res.json();
      const actions = data.actions || [];
      const ideas = actions
        .filter((a: any) => a.type === "meal")
        .map((a: any) => ({
          name: a.title,
          emoji: a.emoji || "🍽️",
          tags: a.detail?.split("·").map((t: string) => t.trim()).filter(Boolean) || ["Family"],
        }));
      setAiMealIdeas(ideas.length > 0 ? ideas : mealIdeas);
    } catch {
      setAiMealIdeas(mealIdeas);
    }
    setAiMealLoading(false);
  };

  // Pantry
  const [pantryItems, setPantryItems] = useState<PantryItem[]>([]);
  const [newPantryItem, setNewPantryItem] = useState("");
  const [newPantryStatus, setNewPantryStatus] = useState<"plenty" | "low" | "out">("plenty");

  // Grocery
  const [groceryItems, setGroceryItems] = useState<GroceryItem[]>(initialGroceryItems);
  const [activeCategory, setActiveCategory] = useState("all");
  const [newGroceryItem, setNewGroceryItem] = useState("");
  const [newGroceryCategory, setNewGroceryCategory] = useState("pantry");
  const [newGroceryPriority, setNewGroceryPriority] = useState<"low" | "medium" | "high">("medium");
  const [editingGroceryId, setEditingGroceryId] = useState<number | null>(null);
  const [editName, setEditName] = useState("");
  const [editQuantity, setEditQuantity] = useState("");
  const [editNotes, setEditNotes] = useState("");

  // localStorage helpers
  const MEALS_KEY = "consuela-meals";
  const PANTRY_KEY = "consuela-pantry";
  const GROCERY_KEY = "consuela-grocery";
  const loadJSON = <T,>(key: string, fallback: T): T => {
    if (typeof window === "undefined") return fallback;
    try { const s = localStorage.getItem(key); return s ? JSON.parse(s) : fallback; }
    catch { return fallback; }
  };

  useEffect(() => {
    const loaded = db.selectMeals();
    const mealDefaults = loaded.length ? loaded : defaultMeals;
    // Check localStorage first
    const saved = loadJSON(MEALS_KEY, mealDefaults);
    setMeals(saved);
    const pantry = db.selectPantry().map((p: any) => ({ id: p.id, item: p.name, status: p.status }));
    const savedPantry = loadJSON(PANTRY_KEY, pantry.length ? pantry : []);
    setPantryItems(savedPantry);
    const grocery = db.selectGrocery();
    const defaultGrocery = grocery.length ? grocery.map(mapDbToGrocery) : initialGroceryItems;
    const savedGrocery = loadJSON(GROCERY_KEY, defaultGrocery);
    setGroceryItems(savedGrocery);
  }, []);

  // Persist on change
  useEffect(() => { if (meals.length) localStorage.setItem(MEALS_KEY, JSON.stringify(meals)); }, [meals]);
  useEffect(() => { if (pantryItems.length) localStorage.setItem(PANTRY_KEY, JSON.stringify(pantryItems)); }, [pantryItems]);
  useEffect(() => { if (groceryItems.length) localStorage.setItem(GROCERY_KEY, JSON.stringify(groceryItems)); }, [groceryItems]);

  // ─── Recipe Catalog ───────────────────────────────────────
  const RECIPES_KEY = "consuela-recipes";
  const defaultRecipes: Recipe[] = [
    { id: 1, name: "Grandma's Meatballs", emoji: "🧆", prepTime: "45 min", cookTime: "30 min", tags: ["Family", "Italian"], ingredients: ["Ground beef", "Breadcrumbs", "Eggs", "Parmesan", "Garlic", "Marinara sauce"], instructions: "1. Mix beef, breadcrumbs, eggs, parmesan, garlic.\n2. Roll into balls.\n3. Brown in pan, then simmer in marinara 30 min.", servings: 6, calories: 380, protein: 28, carbs: 18, fat: 22, createdAt: new Date().toISOString() },
    { id: 2, name: "Chicken Quesadillas", emoji: "🫔", prepTime: "15 min", cookTime: "10 min", tags: ["Quick", "Mexican"], ingredients: ["Chicken breast", "Tortillas", "Cheese", "Salsa", "Sour cream"], instructions: "1. Cook and shred chicken.\n2. Fill tortillas with chicken and cheese.\n3. Pan-fry until golden.", servings: 4, calories: 450, protein: 32, carbs: 35, fat: 18, createdAt: new Date().toISOString() },
  ];
  const [recipes, setRecipes] = useState<Recipe[]>(() => loadJSON(RECIPES_KEY, defaultRecipes));
  useEffect(() => { if (recipes.length) localStorage.setItem(RECIPES_KEY, JSON.stringify(recipes)); }, [recipes]);

  // Recipe editor
  const [showRecipeEditor, setShowRecipeEditor] = useState(false);
  const [editingRecipeId, setEditingRecipeId] = useState<number | null>(null);
  const [recipeForm, setRecipeForm] = useState<Recipe>({ id: 0, name: "", emoji: "📖", prepTime: "", tags: [], ingredients: [], instructions: "", servings: 4, calories: 0, createdAt: "" });

  const startAddRecipe = () => {
    setEditingRecipeId(null); setShowRecipeEditor(true);
    setRecipeForm({ id: Date.now(), name: "", emoji: "📖", prepTime: "30 min", tags: [], ingredients: [""], instructions: "", servings: 4, calories: 500, createdAt: new Date().toISOString() });
  };
  const startEditRecipe = (r: Recipe) => { setEditingRecipeId(r.id); setRecipeForm({ ...r }); setShowRecipeEditor(true); };
  const saveCatalogRecipe = () => {
    if (!recipeForm.name.trim()) return;
    if (editingRecipeId) {
      setRecipes(prev => prev.map(r => r.id === editingRecipeId ? { ...recipeForm, id: editingRecipeId } : r));
    } else {
      setRecipes(prev => [...prev, { ...recipeForm, id: Date.now(), createdAt: new Date().toISOString() }]);
    }
    setShowRecipeEditor(false);
  };
  const deleteCatalogRecipe = (id: number) => { setRecipes(prev => prev.filter(r => r.id !== id)); };
  const addRecipeToPlan = (recipe: Recipe, day: string) => {
    const newMeal: Meal = {
      id: Date.now(), name: recipe.name, emoji: recipe.emoji, time: day, mealType: "dinner",
      prepTime: recipe.prepTime, tags: recipe.tags, ingredients: recipe.ingredients,
      servings: recipe.servings, calories: recipe.calories, instructions: recipe.instructions,
    };
    setMeals(prev => [...prev, newMeal]);
    showToast(`✅ Added ${recipe.name} to ${day}`);
  };
  const addRecipeToGrocery = (recipe: Recipe) => {
    recipe.ingredients.forEach(ing => {
      if (ing.trim()) {
        db.upsertGroceryItem({ name: ing.trim(), category: "pantry", aisle: "1", quantity: "", priority: "medium", needed: true, source: "recipe", autoGenerated: false, userId: "demo" });
      }
    });
    const fresh = db.selectGrocery().map(mapDbToGrocery);
    if (fresh.length) setGroceryItems(fresh);
    showToast(`🛒 Added ${recipe.ingredients.length} items to grocery`);
  };

  const mapDbToGrocery = (g: any): GroceryItem => {
    const cat = g.category || "pantry";
    const catDef = groceryCategories.find(c => c.id === cat);
    return { id: g.id, name: g.name, emoji: catDef?.emoji || "📦", category: cat, aisle: g.aisle || "1", quantity: g.quantity, notes: g.notes, priority: g.priority || "medium", needed: g.needed !== false, manualOverride: g.manualOverride, lastSyncedAt: g.lastSyncedAt, source: g.source, autoGenerated: g.autoGenerated };
  };

  const showToast = (msg: string) => {
    setNotification(msg);
    setTimeout(() => setNotification(null), 3000);
  };

  const activeMeal = meals.find(m => m.time === activeDay);

  // ─── Recipe Creator ───────────────────────────────────────────
  const openRecipeModal = (meal?: Meal) => {
    if (meal) {
      setEditingMealId(meal.id);
      setRecipe({
        name: meal.name,
        emoji: meal.emoji,
        time: meal.time,
        prepTime: meal.prepTime,
        servings: meal.servings,
        calories: meal.calories,
        protein: meal.protein ?? 0,
        carbs: meal.carbs ?? 0,
        fat: meal.fat ?? 0,
        tags: [...meal.tags],
        ingredients: [...meal.ingredients],
        instructions: meal.instructions ?? "",
      });
    } else {
      setEditingMealId(null);
      setRecipe({ ...emptyRecipe, time: activeDay });
    }
    setShowRecipeModal(true);
  };

  const deleteMeal = (id: number) => {
    const meal = meals.find(m => m.id === id);
    setMeals(prev => prev.filter(m => m.id !== id));
    if (meal) showToast(`🗑️ Deleted "${meal.name}"`);
  };

  const updateIngredient = (idx: number, val: string) => {
    const ing = [...recipe.ingredients];
    ing[idx] = val;
    setRecipe(r => ({ ...r, ingredients: ing }));
  };

  const addIngredientRow = () => setRecipe(r => ({ ...r, ingredients: [...r.ingredients, ""] }));
  const removeIngredientRow = (idx: number) => setRecipe(r => ({ ...r, ingredients: r.ingredients.filter((_, i) => i !== idx) }));

  const toggleTag = (tag: string) => {
    setRecipe(r => ({
      ...r,
      tags: r.tags.includes(tag) ? r.tags.filter(t => t !== tag) : [...r.tags, tag],
    }));
  };

  const saveRecipe = () => {
    if (!recipe.name.trim()) return;
    if (editingMealId !== null) {
      // Update existing meal
      const updated: Meal = {
        id: editingMealId,
        name: recipe.name.trim(),
        emoji: recipe.emoji,
        time: recipe.time,
        prepTime: recipe.prepTime || "30 min",
        tags: recipe.tags,
        ingredients: recipe.ingredients.filter(i => i.trim()),
        servings: recipe.servings,
        calories: recipe.calories,
        protein: recipe.protein,
        carbs: recipe.carbs,
        fat: recipe.fat,
        instructions: recipe.instructions,
      };
      setMeals(prev => prev.map(m => m.id === editingMealId ? updated : m));
      if (updated.time !== activeDay) setActiveDay(updated.time);
      showToast(`✅ "${updated.name}" updated!`);
    } else {
      // Create new meal
      const newMeal: Meal = {
        id: Date.now(),
        name: recipe.name.trim(),
        emoji: recipe.emoji,
        time: recipe.time,
        prepTime: recipe.prepTime || "30 min",
        tags: recipe.tags,
        ingredients: recipe.ingredients.filter(i => i.trim()),
        servings: recipe.servings,
        calories: recipe.calories,
        protein: recipe.protein,
        carbs: recipe.carbs,
        fat: recipe.fat,
        instructions: recipe.instructions,
      };
      db.insertMeal(newMeal);
      setMeals(prev => {
        const filtered = prev.filter(m => m.time !== newMeal.time);
        return [...filtered, newMeal];
      });
      setActiveDay(newMeal.time);
      showToast(`✅ "${newMeal.name}" added to ${newMeal.time}!`);
    }
    setShowRecipeModal(false);
    setEditingMealId(null);
    setShowNutrition(false);
  };

  // ─── Grocery ─────────────────────────────────────────────────
  const addGroceryItem = () => {
    const trimmed = newGroceryItem.trim();
    if (!trimmed) return;
    const catDef = groceryCategories.find(c => c.id === newGroceryCategory);
    db.upsertGroceryItem({ name: trimmed, category: newGroceryCategory, aisle: "1", quantity: "", notes: "", priority: newGroceryPriority, needed: true, source: "manual", autoGenerated: false });
    const fresh = db.selectGrocery().map(mapDbToGrocery);
    setGroceryItems(fresh.length ? fresh : [...groceryItems, { id: Date.now(), name: trimmed, emoji: catDef?.emoji || "📦", category: newGroceryCategory, aisle: "1", priority: newGroceryPriority, needed: true }]);
    setNewGroceryItem("");
    showToast(`🛒 Added ${trimmed}`);
  };

  const toggleGroceryNeeded = (id: number) => {
    const item = groceryItems.find(i => i.id === id);
    if (!item) return;
    db.upsertGroceryItem({ ...item, needed: !item.needed, id: item.id });
    setGroceryItems(prev => prev.map(i => i.id === id ? { ...i, needed: !i.needed } : i));
  };

  const deleteGroceryItem = (id: number) => {
    db.deleteGroceryItem(id);
    setGroceryItems(prev => prev.filter(i => i.id !== id));
  };

  const updateGroceryItem = (id: number) => {
    const item = groceryItems.find(i => i.id === id);
    if (!item || !editName.trim()) return;
    db.upsertGroceryItem({ ...item, id, name: editName.trim(), quantity: editQuantity, notes: editNotes });
    setGroceryItems(prev => prev.map(i => i.id === id ? { ...i, name: editName.trim(), quantity: editQuantity, notes: editNotes } : i));
    setEditingGroceryId(null);
    setEditName(""); setEditQuantity(""); setEditNotes("");
  };

  const startEditingGrocery = (item: GroceryItem) => {
    setEditingGroceryId(item.id);
    setEditName(item.name);
    setEditQuantity(item.quantity || "");
    setEditNotes(item.notes || "");
  };

  const handleSyncMealToGrocery = async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncMealPlanToGrocery("demo");
      showToast(`✅ Synced +${result.added} items to grocery`);
      const fresh = db.selectGrocery().map(mapDbToGrocery);
      if (fresh.length) setGroceryItems(fresh);
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Sync failed"}`);
    } finally { setIsSyncing(false); setSyncStatus(""); }
  };

  const handleSyncPantryToGrocery = async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncPantryToGrocery("demo");
      showToast(`✅ Pantry synced: ${result.updated} updated`);
      const fresh = db.selectGrocery().map(mapDbToGrocery);
      if (fresh.length) setGroceryItems(fresh);
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Pantry sync failed"}`);
    } finally { setIsSyncing(false); }
  };

  // ─── Pantry ──────────────────────────────────────────────────
  const addPantryItem = () => {
    const trimmed = newPantryItem.trim();
    if (!trimmed) return;
    const exists = pantryItems.some(p => p.item.toLowerCase() === trimmed.toLowerCase());
    if (exists) { showToast("Item already in pantry"); setNewPantryItem(""); return; }
    const saved = db.upsertPantryItem({ userId: "demo", name: trimmed, status: newPantryStatus });
    setPantryItems(prev => [...prev, { id: saved.id, item: saved.name, status: saved.status }]);
    setNewPantryItem("");
    showToast(`🥫 Added ${trimmed} to pantry`);
  };

  const updatePantryStatus = (id: number, status: "plenty" | "low" | "out") => {
    const item = pantryItems.find(p => p.id === id);
    if (!item) return;
    db.upsertPantryItem({ userId: "demo", name: item.item, status });
    setPantryItems(prev => prev.map(p => p.id === id ? { ...p, status } : p));
  };

  const removePantryItem = (id: number) => {
    setPantryItems(prev => prev.filter(p => p.id !== id));
  };

  const importRecipeFromUrl = (url: string, source: string) => {
    showToast(`📥 Importing from ${source}... (coming soon)`);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    showToast(`📄 Parsing "${file.name}"... (coming soon)`);
    e.target.value = "";
  };

  const neededCount = groceryItems.filter(i => i.needed).length;
  const filteredGrocery = activeCategory === "all" ? groceryItems : groceryItems.filter(i => i.category === activeCategory);

  return (
    <PageShell>
      {/* Toast */}
      {notification && (
        <div
          className={`fixed top-4 left-1/2 -translate-x-1/2 z-[100] flex items-center gap-2 px-4 py-2.5 rounded-2xl text-sm font-medium shadow-2xl border transition-all animate-[slideDown_0.3s_ease] ${
            notification.includes("❌")
              ? "bg-rose-500/20 border-rose-500/30 text-rose-300"
              : "bg-nori-500/20 border-nori-500/30 text-nori-300"
          }`}
          style={{ backdropFilter: "blur(20px)" }}
        >
          {notification}
        </div>
      )}

      <TopBar
        title="Kitchen"
        subtitle={activeTab === "meals" ? "This week" : activeTab === "grocery" ? `${neededCount} items needed` : `${pantryItems.length} items tracked`}
        right={
          activeTab === "meals" ? (
            <button
              onClick={generateAiMeals}
              disabled={aiMealLoading}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-nori-500/15 text-nori-400 text-xs font-medium hover:bg-nori-500/25 transition-colors disabled:opacity-50"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3.5 h-3.5">
                <path d="M12 2l2 7h7l-5.7 4.1 2.2 6.9L12 16l-5.5 4 2.2-6.9L3 9h7z" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              {aiMealLoading ? "Thinking..." : "AI Suggest"}
            </button>
          ) : null
        }
      />

      {/* Tab Bar */}
      <div className="px-4 mb-4">
        <div className="flex rounded-2xl bg-surface-2 p-1 gap-1">
          {([
            { id: "meals", label: "🍽️ Meals" },
            { id: "grocery", label: "🛒 Grocery" },
            { id: "pantry", label: "🥫 Pantry" },
          ] as { id: Tab; label: string }[]).map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 py-2 rounded-xl text-xs font-semibold transition-all duration-200 ${
                activeTab === tab.id
                  ? "bg-nori-500 text-surface-0 shadow-lg shadow-nori-500/25"
                  : "text-text-secondary hover:text-text-primary"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════ */}
      {/* MEALS TAB */}
      {/* ═══════════════════════════════════════════════════════ */}
      {activeTab === "meals" && (
        <div className="px-4 space-y-5 pb-4">
          {/* Weekly strip */}
          <div className="flex gap-2 overflow-x-auto pb-1 -mx-4 px-4">
            {weekDays.map(day => {
              const meal = meals.find(m => m.time === day);
              const isActive = day === activeDay;
              return (
                <button
                  key={day}
                  onClick={() => setActiveDay(day)}
                  className={`shrink-0 flex flex-col items-center gap-1.5 rounded-2xl px-3 py-3 min-w-[72px] transition-all active:scale-95 ${
                    isActive
                      ? "bg-nori-500/15 border border-nori-500/30"
                      : "glass border border-transparent hover:border-surface-4"
                  }`}
                >
                  <span className={`text-xs font-semibold ${isActive ? "text-nori-400" : "text-text-secondary"}`}>{day}</span>
                  <span
                    className="text-2xl"
                    style={{ animation: isActive ? "bounce 1s ease infinite" : "none" }}
                  >
                    {meal?.emoji ?? "➕"}
                  </span>
                  <span className="text-[10px] text-text-muted text-center leading-tight w-full truncate">
                    {meal?.name ?? "Add meal"}
                  </span>
                </button>
              );
            })}
          </div>

          {/* Create Recipe Button */}
          <button
            onClick={() => openRecipeModal()}
            className="w-full flex items-center justify-center gap-2 py-3 rounded-2xl border-2 border-dashed border-nori-500/30 text-nori-400 text-sm font-medium hover:border-nori-500/60 hover:bg-nori-500/5 transition-all group"
          >
            <span className="text-lg group-hover:scale-110 transition-transform" style={{ display: "inline-block" }}>🍳</span>
            Create New Recipe
          </button>

          {/* Active meal detail */}
          {activeMeal && (
            <Card glow>
              <div className="flex items-start gap-3 mb-4">
                <div
                  className="w-14 h-14 rounded-2xl bg-surface-3 flex items-center justify-center text-3xl shrink-0"
                  style={{ animation: "bounceIn 0.4s ease" }}
                >
                  {activeMeal.emoji}
                </div>
                <div className="flex-1 min-w-0">
                  <h2 className="text-text-primary font-bold text-lg leading-tight">{activeMeal.name}</h2>
                  <p className="text-text-secondary text-xs mt-1">{activeMeal.prepTime} · {activeMeal.servings} servings</p>
                  <div className="flex gap-1.5 mt-2 flex-wrap">
                    {activeMeal.tags.map(t => <Badge key={t} variant="green">{t}</Badge>)}
                  </div>
                </div>
              </div>

              {/* Nutrition toggle */}
              <button
                onClick={() => setShowNutrition(!showNutrition)}
                className="w-full flex items-center justify-between py-2 border-t border-surface-3 text-text-secondary text-xs hover:text-text-primary transition-colors"
              >
                <span className="flex items-center gap-1.5">📊 Nutrition info</span>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className={`w-4 h-4 transition-transform ${showNutrition ? "rotate-180" : ""}`}>
                  <path d="M6 9l6 6 6-6" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </button>

              {showNutrition && (
                <div className="mt-2 grid grid-cols-4 gap-2">
                  {[
                    { label: "Calories", value: activeMeal.calories, unit: "kcal", color: "#f59e0b" },
                    { label: "Protein", value: activeMeal.protein ?? 32, unit: "g", color: "#22c55e" },
                    { label: "Carbs", value: activeMeal.carbs ?? 48, unit: "g", color: "#3b82f6" },
                    { label: "Fat", value: activeMeal.fat ?? 14, unit: "g", color: "#ec4899" },
                  ].map(n => (
                    <div key={n.label} className="bg-surface-2 rounded-xl p-2.5 text-center">
                      <p className="text-text-primary font-bold text-base" style={{ color: n.color }}>{n.value}</p>
                      <p className="text-[10px] text-text-muted">{n.unit}</p>
                      <p className="text-[10px] text-text-muted">{n.label}</p>
                    </div>
                  ))}
                </div>
              )}

              {/* Ingredients */}
              <div className="mt-4">
                <p className="text-text-secondary text-xs font-medium mb-2">🧂 Ingredients</p>
                <div className="flex flex-wrap gap-1.5">
                  {activeMeal.ingredients.map(ing => (
                    <span key={ing} className="px-2.5 py-1 rounded-lg bg-surface-2 text-text-secondary text-xs">{ing}</span>
                  ))}
                </div>
              </div>

              {/* Instructions if present */}
              {activeMeal.instructions && (
                <div className="mt-4">
                  <p className="text-text-secondary text-xs font-medium mb-2">📋 Instructions</p>
                  <p className="text-text-secondary text-xs leading-relaxed">{activeMeal.instructions}</p>
                </div>
              )}

              {/* Actions */}
              <div className="flex gap-2 mt-4">
                <button
                  onClick={() => activeMeal && openRecipeModal(activeMeal)}
                  className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl glass text-text-secondary text-sm font-medium hover:text-text-primary hover:bg-surface-2 transition-colors"
                >
                  ✏️ Edit
                </button>
                <button
                  onClick={() => activeMeal && deleteMeal(activeMeal.id)}
                  className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-rose-500/10 text-rose-400 text-sm font-medium hover:bg-rose-500/20 transition-colors"
                >
                  🗑️ Delete
                </button>
              </div>
              <div className="flex gap-2 mt-2">
                <button
                  onClick={() => setActiveTab("grocery")}
                  className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-nori-500/15 text-nori-400 text-sm font-medium hover:bg-nori-500/25 transition-colors"
                >
                  🛒 Grocery List
                </button>
                <button
                  onClick={handleSyncMealToGrocery}
                  disabled={isSyncing}
                  className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl glass text-text-secondary text-sm font-medium hover:text-text-primary transition-colors disabled:opacity-60"
                >
                  🔄 {isSyncing ? "Syncing..." : "Sync to Grocery"}
                </button>
              </div>
            </Card>
          )}

          {/* AI Suggestions */}
          {showAiSuggestions && (
            <section>
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-text-primary font-semibold text-sm">✨ Consuela Suggests</h3>
                <Badge variant="violet">AI picks</Badge>
              </div>
              <div className="grid grid-cols-2 gap-2">
                {(aiMealIdeas.length > 0 ? aiMealIdeas : mealIdeas).map(idea => (
                  <Card key={idea.name} className="!p-3 cursor-pointer hover:border-nori-500/30 transition-colors"
                    onClick={() => {
                      const newMeal: Meal = {
                        id: Date.now(),
                        name: idea.name,
                        emoji: idea.emoji,
                        time: activeDay,
                        prepTime: "30 min",
                        tags: idea.tags,
                        ingredients: [],
                        servings: 4,
                        calories: 500,
                      };
                      db.insertMeal(newMeal);
                      setMeals(prev => [...prev, newMeal]);
                      showToast(`✅ Added ${idea.name} to ${activeDay}`);
                    }}
                  >
                    <div className="flex flex-col items-center gap-2 text-center">
                      <span className="text-2xl" style={{ animation: "float 3s ease-in-out infinite" }}>{idea.emoji}</span>
                      <p className="text-text-primary text-xs font-medium leading-tight">{idea.name}</p>
                      <div className="flex gap-1 flex-wrap justify-center">
                        {idea.tags.map(t => <Badge key={t} variant="gray">{t}</Badge>)}
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
              {aiMealLoading && (
                <p className="text-text-muted text-xs text-center mt-2">Asking Consuela for ideas...</p>
              )}
            </section>
          )}

          {/* Import Recipes */}
          <section className="pb-2">
            <h3 className="text-text-primary font-semibold text-sm mb-3">📥 Import Recipes</h3>
            <div className="grid grid-cols-2 gap-2">
              {[
                { label: "📌 Pinterest", source: "Pinterest" },
                { label: "🎵 TikTok", source: "TikTok" },
              ].map(s => (
                <button
                  key={s.source}
                  onClick={() => { const url = prompt(`Enter ${s.source} URL:`); if (url) importRecipeFromUrl(url, s.source); }}
                  className="flex items-center justify-center gap-2 px-3 py-3 rounded-xl text-xs font-medium bg-nori-500/10 text-nori-400 border border-nori-500/20 hover:bg-nori-500/20 transition-all"
                >
                  {s.label}
                </button>
              ))}
              <button
                onClick={() => document.getElementById("recipe-file-upload")?.click()}
                className="flex items-center justify-center gap-2 px-3 py-3 rounded-xl text-xs font-medium glass text-text-secondary border border-surface-3 hover:text-text-primary transition-all"
              >
                📄 Upload File
              </button>
              <button
                onClick={() => document.getElementById("recipe-pdf-upload")?.click()}
                className="flex items-center justify-center gap-2 px-3 py-3 rounded-xl text-xs font-medium glass text-text-secondary border border-surface-3 hover:text-text-primary transition-all"
              >
                🗒️ Upload PDF
              </button>
            </div>
            <input type="file" id="recipe-file-upload" accept=".txt,.json,.csv" className="hidden" onChange={handleFileUpload} />
            <input type="file" id="recipe-pdf-upload" accept=".pdf" className="hidden" onChange={handleFileUpload} />
          </section>

          {/* Family Preferences */}
          <section className="pb-4">
            <h3 className="text-text-primary font-semibold text-sm mb-3">👨‍👩‍👧‍👦 Family Preferences</h3>
            <div className="flex flex-wrap gap-2">
              {[
                { label: "🥦 Vegetarian options", active: true },
                { label: "🐟 Seafood twice/week", active: true },
                { label: "🌶️ Not too spicy", active: true },
                { label: "🥜 Nut-free (Jasmine)", active: true },
                { label: "🍖 Low-carb", active: false },
              ].map(pref => (
                <span
                  key={pref.label}
                  className={`px-3 py-1.5 rounded-full text-xs font-medium transition-all ${
                    pref.active
                      ? "bg-nori-500/15 text-nori-400 border border-nori-500/20"
                      : "glass text-text-muted border border-surface-3"
                  }`}
                >
                  {pref.label}
                </span>
              ))}
            </div>
          </section>
        </div>
      )}

      {/* ═══════════════════════════════════════════════════════ */}
      {/* GROCERY TAB */}
      {/* ═══════════════════════════════════════════════════════ */}
      {activeTab === "grocery" && (
        <div className="px-4 space-y-4 pb-4">
          {/* Quick Add */}
          <Card className="!p-4">
            <p className="text-text-secondary text-xs font-medium mb-3">➕ Add Item</p>
            <div className="space-y-3">
              <div className="flex gap-2">
                <input
                  value={newGroceryItem}
                  onChange={e => setNewGroceryItem(e.target.value)}
                  onKeyDown={e => e.key === "Enter" && addGroceryItem()}
                  placeholder="What do you need?"
                  className="flex-1 bg-transparent text-text-primary text-sm outline-none placeholder:text-text-muted"
                />
                <select
                  value={newGroceryCategory}
                  onChange={e => setNewGroceryCategory(e.target.value)}
                  className="bg-surface-2 text-text-secondary text-xs rounded-lg px-2 outline-none"
                >
                  {groceryCategories.map(cat => (
                    <option key={cat.id} value={cat.id}>{cat.emoji} {cat.name}</option>
                  ))}
                </select>
              </div>
              <div className="flex gap-2">
                <select
                  value={newGroceryPriority}
                  onChange={e => setNewGroceryPriority(e.target.value as "low" | "medium" | "high")}
                  className="bg-surface-2 text-text-secondary text-xs rounded-lg px-2 outline-none"
                >
                  <option value="low">🟢 Low</option>
                  <option value="medium">🟡 Medium</option>
                  <option value="high">🔴 High</option>
                </select>
                <button
                  onClick={addGroceryItem}
                  disabled={!newGroceryItem.trim()}
                  className="flex-1 px-4 py-2 rounded-xl bg-nori-500 text-surface-0 text-xs font-semibold hover:bg-nori-400 disabled:opacity-50 transition-colors"
                >
                  Add to List
                </button>
              </div>
            </div>
          </Card>

          {/* Sync Buttons */}
          <div className="flex gap-2">
            <button
              onClick={handleSyncMealToGrocery}
              disabled={isSyncing}
              className="flex-1 py-2 rounded-xl bg-nori-500/10 text-nori-400 text-xs font-medium border border-nori-500/20 hover:bg-nori-500/20 transition-colors disabled:opacity-60"
            >
              🍽️ Sync from Meals
            </button>
            <button
              onClick={handleSyncPantryToGrocery}
              disabled={isSyncing}
              className="flex-1 py-2 rounded-xl glass text-text-secondary text-xs font-medium border border-surface-3 hover:text-text-primary transition-colors disabled:opacity-60"
            >
              🥫 Sync from Pantry
            </button>
          </div>

          {/* Category Filter */}
          <div className="flex gap-2 overflow-x-auto pb-1 -mx-4 px-4">
            <button
              onClick={() => setActiveCategory("all")}
              className={`shrink-0 px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${activeCategory === "all" ? "bg-nori-500 text-surface-0" : "glass text-text-secondary hover:text-text-primary"}`}
            >
              All
            </button>
            {groceryCategories.map(cat => (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={`shrink-0 flex items-center gap-1 px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${activeCategory === cat.id ? "bg-nori-500 text-surface-0" : "glass text-text-secondary hover:text-text-primary"}`}
              >
                {cat.emoji} {cat.name}
              </button>
            ))}
          </div>

          {/* Grocery Items by Category */}
          {groceryCategories.map(cat => {
            const catItems = filteredGrocery.filter(i => i.category === cat.id);
            if (catItems.length === 0) return null;
            const neededCnt = catItems.filter(i => i.needed).length;
            return (
              <section key={cat.id}>
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-lg">{cat.emoji}</span>
                    <h3 className="text-text-primary font-semibold text-sm">{cat.name}</h3>
                  </div>
                  <span className="text-xs text-nori-400">{neededCnt} needed</span>
                </div>
                <Card className="!p-0 overflow-hidden">
                  <div className="divide-y divide-surface-3">
                    {catItems.map(item => (
                      <div key={item.id} className="p-3">
                        {editingGroceryId === item.id ? (
                          <div className="space-y-2">
                            <div className="flex gap-2">
                              <input value={editName} onChange={e => setEditName(e.target.value)} placeholder="Name" className="flex-1 bg-transparent text-text-primary text-sm outline-none" />
                              <input value={editQuantity} onChange={e => setEditQuantity(e.target.value)} placeholder="Qty" className="w-16 bg-surface-2 text-text-secondary text-xs rounded px-2 outline-none" />
                            </div>
                            <input value={editNotes} onChange={e => setEditNotes(e.target.value)} placeholder="Notes (optional)" className="w-full bg-transparent text-text-secondary text-xs outline-none" />
                            <div className="flex gap-2">
                              <button onClick={() => updateGroceryItem(item.id)} className="px-3 py-1 rounded-lg bg-nori-500 text-surface-0 text-xs font-medium">Save</button>
                              <button onClick={() => { setEditingGroceryId(null); setEditName(""); }} className="px-3 py-1 rounded-lg text-text-secondary text-xs">Cancel</button>
                            </div>
                          </div>
                        ) : (
                          <div className="flex items-center gap-3">
                            <button
                              onClick={() => toggleGroceryNeeded(item.id)}
                              className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 transition-all ${item.needed ? "border-2 border-surface-4" : "bg-nori-500"}`}
                            >
                              {!item.needed && (
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={3} className="w-3.5 h-3.5 text-surface-0">
                                  <path d="M5 12l5 5 9-9" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                              )}
                            </button>
                            <span className="text-lg">{item.emoji}</span>
                            <div className="flex-1 min-w-0">
                              <p className={`text-sm font-medium ${!item.needed ? "text-text-muted line-through" : "text-text-primary"}`}>{item.name}</p>
                              {item.quantity && <p className="text-xs text-text-muted">Qty: {item.quantity}</p>}
                            </div>
                            <Badge variant={item.priority === "high" ? "rose" : item.priority === "medium" ? "amber" : "green"}>
                              {item.priority}
                            </Badge>
                            <div className="flex gap-1">
                              <button onClick={() => startEditingGrocery(item)} className="p-1.5 rounded-lg hover:bg-surface-2 text-text-muted hover:text-text-primary transition-colors">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3.5 h-3.5">
                                  <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7" strokeLinecap="round" strokeLinejoin="round" />
                                  <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                              </button>
                              <button onClick={() => deleteGroceryItem(item.id)} className="p-1.5 rounded-lg hover:bg-rose-500/10 text-text-muted hover:text-rose-400 transition-colors">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3.5 h-3.5">
                                  <path d="M3 6h18M19 6l-1 14H6L5 6M8 6V4h8v2" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                              </button>
                            </div>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </Card>
              </section>
            );
          })}

          {/* Bulk Actions */}
          <div className="flex gap-2 pb-4">
            <button
              onClick={() => {
                groceryItems.forEach(item => db.upsertGroceryItem({ ...item, needed: true, id: item.id }));
                setGroceryItems(prev => prev.map(i => ({ ...i, needed: true })));
              }}
              className="flex-1 py-2 rounded-xl bg-surface-2 text-text-secondary text-xs font-medium hover:bg-nori-500/15 hover:text-nori-400 transition-colors"
            >
              Mark All Needed
            </button>
            <button
              onClick={() => {
                const toRemove = groceryItems.filter(i => !i.needed);
                toRemove.forEach(i => db.deleteGroceryItem(i.id));
                setGroceryItems(prev => prev.filter(i => i.needed));
              }}
              className="flex-1 py-2 rounded-xl bg-surface-2 text-text-secondary text-xs font-medium hover:bg-rose-500/15 hover:text-rose-400 transition-colors"
            >
              Clear Completed
            </button>
          </div>
        </div>
      )}

      {/* ═══════════════════════════════════════════════════════ */}
      {/* PANTRY TAB */}
      {/* ═══════════════════════════════════════════════════════ */}
      {activeTab === "pantry" && (
        <div className="px-4 space-y-4 pb-4">
          {/* Stats */}
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: "Plenty", count: pantryItems.filter(p => p.status === "plenty").length, emoji: "✅", color: "text-nori-400" },
              { label: "Running Low", count: pantryItems.filter(p => p.status === "low").length, emoji: "⚠️", color: "text-amber-400" },
              { label: "Out of Stock", count: pantryItems.filter(p => p.status === "out").length, emoji: "❌", color: "text-rose-400" },
            ].map(stat => (
              <Card key={stat.label} className="!p-3 text-center">
                <span className="text-2xl block mb-1" style={{ animation: "float 3s ease-in-out infinite" }}>{stat.emoji}</span>
                <p className={`text-xl font-bold ${stat.color}`}>{stat.count}</p>
                <p className="text-[10px] text-text-muted">{stat.label}</p>
              </Card>
            ))}
          </div>

          {/* Add Item */}
          <Card className="!p-4">
            <p className="text-text-secondary text-xs font-medium mb-3">➕ Add to Pantry</p>
            <div className="flex gap-2">
              <input
                value={newPantryItem}
                onChange={e => setNewPantryItem(e.target.value)}
                onKeyDown={e => e.key === "Enter" && addPantryItem()}
                placeholder="Item name..."
                className="flex-1 bg-transparent text-text-primary text-sm outline-none placeholder:text-text-muted"
              />
              <select
                value={newPantryStatus}
                onChange={e => setNewPantryStatus(e.target.value as "plenty" | "low" | "out")}
                className="bg-surface-2 text-text-secondary text-xs rounded-lg px-2 outline-none"
              >
                <option value="plenty">✅ Plenty</option>
                <option value="low">⚠️ Low</option>
                <option value="out">❌ Out</option>
              </select>
              <button
                onClick={addPantryItem}
                disabled={!newPantryItem.trim()}
                className="px-4 py-2 rounded-xl bg-nori-500 text-surface-0 text-xs font-semibold hover:bg-nori-400 disabled:opacity-50 transition-colors"
              >
                Add
              </button>
            </div>
          </Card>

          {/* Sync */}
          <button
            onClick={handleSyncPantryToGrocery}
            disabled={isSyncing}
            className="w-full py-2.5 rounded-xl bg-nori-500/10 text-nori-400 text-sm font-medium border border-nori-500/20 hover:bg-nori-500/20 transition-colors disabled:opacity-60 flex items-center justify-center gap-2"
          >
            🔄 {isSyncing ? "Syncing..." : "Sync Low/Out items → Grocery"}
          </button>

          {/* Pantry List */}
          {pantryItems.length > 0 ? (
            <Card className="!p-0 overflow-hidden">
              <div className="divide-y divide-surface-3">
                {pantryItems.map(p => (
                  <div key={p.id} className="flex items-center gap-3 p-3">
                    <span className="text-xl">
                      {p.status === "plenty" ? "✅" : p.status === "low" ? "⚠️" : "❌"}
                    </span>
                    <span className="flex-1 text-text-primary text-sm font-medium">{p.item}</span>
                    <div className="flex items-center gap-1">
                      {(["plenty", "low", "out"] as const).map(s => (
                        <button
                          key={s}
                          onClick={() => updatePantryStatus(p.id, s)}
                          className={`px-2 py-0.5 rounded-lg text-[10px] font-medium transition-all ${
                            p.status === s
                              ? s === "plenty" ? "bg-nori-500/20 text-nori-400" : s === "low" ? "bg-amber-500/20 text-amber-400" : "bg-rose-500/20 text-rose-400"
                              : "bg-surface-2 text-text-muted hover:text-text-primary"
                          }`}
                        >
                          {s}
                        </button>
                      ))}
                      <button
                        onClick={() => removePantryItem(p.id)}
                        className="ml-1 p-1 rounded-lg text-text-muted hover:text-rose-400 hover:bg-rose-500/10 transition-colors"
                      >
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3.5 h-3.5">
                          <path d="M18 6L6 18M6 6l12 12" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          ) : (
            <div className="text-center py-10">
              <span className="text-4xl block mb-3" style={{ animation: "float 3s ease-in-out infinite" }}>🥫</span>
              <p className="text-text-secondary text-sm">Your pantry is empty</p>
              <p className="text-text-muted text-xs mt-1">Add items above to track your stock</p>
            </div>
          )}

          {/* Ask Consuela */}
          <Link
            href="/chat?q=What+can+I+make+with+my+pantry+items"
            className="flex items-center justify-center gap-2 py-3 rounded-2xl bg-surface-2 text-text-secondary text-sm font-medium hover:bg-nori-500/10 hover:text-nori-400 transition-all border border-surface-3 hover:border-nori-500/20"
          >
            ✨ Ask Consuela what to cook with my pantry
          </Link>
        </div>
      )}

      {/* ═══════════════════════════════════════════════════════ */}
      {/* RECIPE CREATOR MODAL */}
      {/* ═══════════════════════════════════════════════════════ */}
      {showRecipeModal && (
        <div className="fixed inset-0 z-[200] flex flex-col" style={{ background: "rgba(0,0,0,0.7)", backdropFilter: "blur(12px)" }}>
          {/* Modal sheet */}
          <div
            className="absolute bottom-0 left-0 right-0 rounded-t-3xl flex flex-col overflow-hidden"
            style={{
              background: "var(--color-surface-1)",
              border: "1px solid var(--color-surface-4)",
              maxHeight: "92vh",
            }}
          >
            {/* Handle */}
            <div className="flex justify-center pt-3 pb-1">
              <div className="w-10 h-1 rounded-full bg-surface-4" />
            </div>

            {/* Header */}
            <div className="px-5 pb-4 flex items-center justify-between border-b border-surface-3">
              <div>
                <h2 className="text-text-primary font-bold text-lg">{editingMealId !== null ? "✏️ Edit Recipe" : "🍳 Create Recipe"}</h2>
                <p className="text-text-muted text-xs">{editingMealId !== null ? "Update your recipe" : "Add your own recipe to the meal planner"}</p>
              </div>
              <button
                onClick={() => setShowRecipeModal(false)}
                className="w-9 h-9 rounded-xl glass flex items-center justify-center text-text-secondary hover:text-text-primary transition-colors"
              >
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
                  <path d="M18 6L6 18M6 6l12 12" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </button>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto px-5 py-4 space-y-5">
              {/* Emoji + Name */}
              <div className="flex items-center gap-3">
                <div className="relative">
                  <button
                    onClick={() => setShowEmojiPicker(!showEmojiPicker)}
                    className="w-16 h-16 rounded-2xl bg-surface-2 flex items-center justify-center text-4xl hover:bg-surface-3 transition-colors border-2 border-dashed border-surface-4 hover:border-nori-500/40"
                  >
                    {recipe.emoji}
                  </button>
                  {showEmojiPicker && (
                    <div
                      className="absolute top-full left-0 mt-2 z-50 p-3 rounded-2xl shadow-2xl"
                      style={{ background: "var(--color-surface-2)", border: "1px solid var(--color-surface-4)", width: "260px" }}
                    >
                      <p className="text-text-muted text-xs mb-2">Choose an emoji</p>
                      <div className="grid grid-cols-8 gap-1">
                        {foodEmojis.map(e => (
                          <button
                            key={e}
                            onClick={() => { setRecipe(r => ({ ...r, emoji: e })); setShowEmojiPicker(false); }}
                            className={`w-8 h-8 rounded-lg text-xl flex items-center justify-center hover:bg-nori-500/20 transition-all hover:scale-110 ${recipe.emoji === e ? "bg-nori-500/20" : ""}`}
                          >
                            {e}
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
                <input
                  value={recipe.name}
                  onChange={e => setRecipe(r => ({ ...r, name: e.target.value }))}
                  placeholder="Recipe name..."
                  className="flex-1 bg-surface-2 text-text-primary text-base font-semibold rounded-2xl px-4 py-3 outline-none placeholder:text-text-muted border border-surface-3 focus:border-nori-500/50 transition-colors"
                />
              </div>

              {/* Details Row */}
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="text-text-muted text-xs mb-1.5 block">Day</label>
                  <select
                    value={recipe.time}
                    onChange={e => setRecipe(r => ({ ...r, time: e.target.value }))}
                    className="w-full bg-surface-2 text-text-primary text-sm rounded-xl px-3 py-2.5 outline-none border border-surface-3 focus:border-nori-500/50"
                  >
                    {weekDays.map(d => <option key={d} value={d}>{d}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-text-muted text-xs mb-1.5 block">Prep Time</label>
                  <input
                    value={recipe.prepTime}
                    onChange={e => setRecipe(r => ({ ...r, prepTime: e.target.value }))}
                    placeholder="e.g. 30 min"
                    className="w-full bg-surface-2 text-text-primary text-sm rounded-xl px-3 py-2.5 outline-none border border-surface-3 focus:border-nori-500/50 placeholder:text-text-muted"
                  />
                </div>
                <div>
                  <label className="text-text-muted text-xs mb-1.5 block">Servings</label>
                  <input
                    type="number"
                    value={recipe.servings}
                    onChange={e => setRecipe(r => ({ ...r, servings: Number(e.target.value) }))}
                    min={1}
                    className="w-full bg-surface-2 text-text-primary text-sm rounded-xl px-3 py-2.5 outline-none border border-surface-3 focus:border-nori-500/50"
                  />
                </div>
              </div>

              {/* Nutrition */}
              <div>
                <p className="text-text-secondary text-xs font-semibold mb-2">📊 Nutrition (per serving)</p>
                <div className="grid grid-cols-4 gap-2">
                  {[
                    { key: "calories", label: "Calories", unit: "kcal", color: "#f59e0b" },
                    { key: "protein", label: "Protein", unit: "g", color: "#22c55e" },
                    { key: "carbs", label: "Carbs", unit: "g", color: "#3b82f6" },
                    { key: "fat", label: "Fat", unit: "g", color: "#ec4899" },
                  ].map(n => (
                    <div key={n.key} className="bg-surface-2 rounded-xl p-2.5 text-center border border-surface-3">
                      <p className="text-[10px] font-medium mb-1" style={{ color: n.color }}>{n.label}</p>
                      <input
                        type="number"
                        value={(recipe as any)[n.key]}
                        onChange={e => setRecipe(r => ({ ...r, [n.key]: Number(e.target.value) }))}
                        min={0}
                        className="w-full bg-transparent text-text-primary text-sm font-bold text-center outline-none"
                      />
                      <p className="text-[10px] text-text-muted">{n.unit}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Ingredients */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <p className="text-text-secondary text-xs font-semibold">🧂 Ingredients</p>
                  <button onClick={addIngredientRow} className="text-nori-400 text-xs hover:text-nori-300">+ Add</button>
                </div>
                <div className="space-y-2">
                  {recipe.ingredients.map((ing, idx) => (
                    <div key={idx} className="flex items-center gap-2">
                      <span className="text-text-muted text-xs w-5 text-center">{idx + 1}.</span>
                      <input
                        value={ing}
                        onChange={e => updateIngredient(idx, e.target.value)}
                        placeholder={`Ingredient ${idx + 1}...`}
                        className="flex-1 bg-surface-2 text-text-primary text-sm rounded-xl px-3 py-2 outline-none border border-surface-3 focus:border-nori-500/50 placeholder:text-text-muted"
                      />
                      {recipe.ingredients.length > 1 && (
                        <button onClick={() => removeIngredientRow(idx)} className="p-1.5 text-text-muted hover:text-rose-400 transition-colors">
                          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-4 h-4">
                            <path d="M18 6L6 18M6 6l12 12" strokeLinecap="round" strokeLinejoin="round" />
                          </svg>
                        </button>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Tags */}
              <div>
                <p className="text-text-secondary text-xs font-semibold mb-2">🏷️ Tags</p>
                <div className="flex flex-wrap gap-1.5">
                  {RECIPE_TAGS.map(tag => (
                    <button
                      key={tag}
                      onClick={() => toggleTag(tag)}
                      className={`px-2.5 py-1 rounded-full text-xs font-medium transition-all ${
                        recipe.tags.includes(tag)
                          ? "bg-nori-500/20 text-nori-400 border border-nori-500/30"
                          : "bg-surface-2 text-text-muted border border-surface-3 hover:text-text-primary"
                      }`}
                    >
                      {tag}
                    </button>
                  ))}
                </div>
              </div>

              {/* Instructions */}
              <div>
                <p className="text-text-secondary text-xs font-semibold mb-2">📋 Instructions (optional)</p>
                <textarea
                  value={recipe.instructions}
                  onChange={e => setRecipe(r => ({ ...r, instructions: e.target.value }))}
                  placeholder="Step-by-step instructions..."
                  rows={3}
                  className="w-full bg-surface-2 text-text-primary text-sm rounded-xl px-4 py-3 outline-none border border-surface-3 focus:border-nori-500/50 placeholder:text-text-muted resize-none"
                />
              </div>
            </div>

            {/* Footer Save Button */}
            <div className="px-5 py-4 border-t border-surface-3" style={{ paddingBottom: "calc(1rem + env(safe-area-inset-bottom))" }}>
              <button
                onClick={saveRecipe}
                disabled={!recipe.name.trim()}
                className="w-full py-4 rounded-2xl bg-nori-500 text-surface-0 font-bold text-base hover:bg-nori-400 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-nori-500/30 flex items-center justify-center gap-2"
              >
                <span className="text-xl">{editingMealId !== null ? "💾" : "🍳"}</span>
                {editingMealId !== null ? "Save Changes" : "Save Recipe"}
              </button>
            </div>
          </div>
        </div>
      )}

      <style jsx global>{`
        @keyframes slideDown {
          from { opacity: 0; transform: translateX(-50%) translateY(-10px); }
          to { opacity: 1; transform: translateX(-50%) translateY(0); }
        }
        @keyframes bounceIn {
          0% { transform: scale(0.8); opacity: 0.5; }
          60% { transform: scale(1.1); }
          100% { transform: scale(1); opacity: 1; }
        }
        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-4px); }
        }
        @keyframes bounce {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-3px); }
        }
      `}</style>
    </PageShell>
  );
}

export default function MealHubPage() {
  return (
    <Suspense fallback={<div className="flex items-center justify-center min-h-screen"><div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary-500"></div></div>}>
      <MealHubContent />
    </Suspense>
  );
}
