import { useState, useEffect, useCallback } from "react";
import { GroceryItem } from "@/types/meals";
import { initialGroceryItems, groceryCategories } from "@/data/meals";
import { mealSyncService } from "@/services/mealSync";

const RECENTLY_BOUGHT_KEY = "consuela-recently-bought";

const loadJSON = <T,>(key: string, fallback: T): T => {
  if (typeof window === "undefined") return fallback;
  try {
    const s = localStorage.getItem(key);
    return s ? JSON.parse(s) : fallback;
  } catch {
    return fallback;
  }
};

/**
 * Map a PocketBase grocery record to the GroceryItem UI type.
 */
const mapDbToGrocery = (g: any): GroceryItem => {
  const cat = g.category || "pantry";
  const catDef = groceryCategories.find((c) => c.id === cat);
  return {
    id: g.id,
    name: g.name,
    emoji: catDef?.emoji || "📦",
    category: cat,
    aisle: g.aisle || "1",
    quantity: g.quantity,
    notes: g.notes,
    priority: g.priority || "medium",
    needed: g.needed !== false,
    manualOverride: g.manualOverride,
    lastSyncedAt: g.lastSyncedAt,
    source: g.source,
    autoGenerated: g.autoGenerated,
  };
};

export function useGrocery(showToast: (msg: string) => void) {
  const [groceryItems, setGroceryItems] = useState<GroceryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState("all");
  const [isSyncing, setIsSyncing] = useState(false);
  const [recentlyBought, setRecentlyBought] = useState<
    { name: string; emoji: string; category: string }[]
  >([]);

  // Fetch grocery items from API on mount
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        setLoading(true);
        const res = await fetch("/api/grocery");
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        const items: GroceryItem[] = (data.grocery || []).map(mapDbToGrocery);
        if (!cancelled) {
          setGroceryItems(items.length > 0 ? items : initialGroceryItems);
          setError(null);
        }
      } catch (e: any) {
        if (!cancelled) {
          setGroceryItems(initialGroceryItems);
          setError(e?.message || "Failed to load grocery list");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    // recentlyBought is a UI preference — keep in localStorage
    setRecentlyBought(
      loadJSON<{ name: string; emoji: string; category: string }[]>(
        RECENTLY_BOUGHT_KEY,
        []
      )
    );
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    localStorage.setItem(RECENTLY_BOUGHT_KEY, JSON.stringify(recentlyBought));
  }, [recentlyBought]);

  const addGroceryItem = useCallback(
    async (
      name: string,
      category: string,
      priority: "low" | "medium" | "high",
      emojiOverride?: string
    ) => {
      const trimmed = name.trim();
      if (!trimmed) return;
      const catDef = groceryCategories.find((c) => c.id === category);
      const itemEmoji = emojiOverride || catDef?.emoji || "📦";

      // Optimistically add locally
      const tempItem = {
        id: `temp-${Date.now()}`,
        name: trimmed,
        emoji: itemEmoji,
        category,
        aisle: "1",
        priority,
        needed: true,
      };
      setGroceryItems((prev) => [...prev, tempItem as any]);

      // Persist to API
      try {
        const res = await fetch("/api/grocery", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            name: trimmed,
            category,
            aisle: "1",
            quantity: "",
            notes: "",
            priority,
            needed: true,
            source: "manual",
            autoGenerated: false,
          }),
        });
        if (res.ok) {
          const data = await res.json();
          const saved = mapDbToGrocery(data.item);
          // Replace temp item with real one from API
          setGroceryItems((prev) =>
            prev.map((i) => ((i as any).id === (tempItem as any).id ? saved : i))
          );
        }
      } catch {
        // Keep optimistic item on network failure
      }

      // Track in recently bought (max 8, deduplicated by name)
      setRecentlyBought((prev) => {
        const filtered = prev.filter(
          (r) => r.name.toLowerCase() !== trimmed.toLowerCase()
        );
        return [{ name: trimmed, emoji: itemEmoji, category }, ...filtered].slice(0, 8);
      });
      showToast(`🛒 Added ${trimmed}`);
    },
    [showToast]
  );

  const clearRecentlyBought = useCallback(() => {
    setRecentlyBought([]);
    localStorage.removeItem(RECENTLY_BOUGHT_KEY);
  }, []);

  const toggleGroceryNeeded = useCallback(
    async (id: string | number) => {
      const item = groceryItems.find((i) => i.id === id);
      if (!item) return;
      const newNeeded = !item.needed;
      // Optimistic update
      setGroceryItems((prev) =>
        prev.map((i) => (i.id === id ? { ...i, needed: newNeeded } : i))
      );
      try {
        await fetch("/api/grocery", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id, needed: newNeeded }),
        });
      } catch {
        // Revert on failure
        setGroceryItems((prev) =>
          prev.map((i) => (i.id === id ? { ...i, needed: item.needed } : i))
        );
      }
    },
    [groceryItems]
  );

  const deleteGroceryItem = useCallback(async (id: string | number) => {
    // Optimistic removal
    let removedItem: GroceryItem | undefined;
    setGroceryItems((prev) => {
      removedItem = prev.find((i) => i.id === id);
      return prev.filter((i) => i.id !== id);
    });
    try {
      await fetch(`/api/grocery?id=${id}`, { method: "DELETE" });
    } catch {
      // Revert on failure
      if (removedItem) {
        setGroceryItems((prev) => [...prev, removedItem!]);
      }
    }
  }, []);

  const updateGroceryItem = useCallback(
    async (
      id: string | number,
      updates: { name: string; quantity: string; notes: string }
    ) => {
      const item = groceryItems.find((i) => i.id === id);
      if (!item || !updates.name.trim()) return;
      // Optimistic update
      setGroceryItems((prev) =>
        prev.map((i) =>
          i.id === id
            ? { ...i, name: updates.name.trim(), quantity: updates.quantity, notes: updates.notes }
            : i
        )
      );
      try {
        await fetch("/api/grocery", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id, ...updates }),
        });
      } catch {
        // Revert on failure
        setGroceryItems((prev) =>
          prev.map((i) => (i.id === id ? item : i))
        );
      }
    },
    [groceryItems]
  );

  const syncMealToGrocery = useCallback(async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncMealPlanToGrocery("demo");
      showToast(`✅ Synced +${result.added} items to grocery`);
      // Re-fetch from API to get updated list
      const res = await fetch("/api/grocery");
      if (res.ok) {
        const data = await res.json();
        const fresh = (data.grocery || []).map(mapDbToGrocery);
        if (fresh.length) setGroceryItems(fresh);
      }
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Sync failed"}`);
    } finally {
      setIsSyncing(false);
    }
  }, [isSyncing, showToast]);

  const syncPantryToGrocery = useCallback(async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncPantryToGrocery("demo");
      showToast(`✅ Pantry synced: ${result.updated} updated`);
      // Re-fetch from API to get updated list
      const res = await fetch("/api/grocery");
      if (res.ok) {
        const data = await res.json();
        const fresh = (data.grocery || []).map(mapDbToGrocery);
        if (fresh.length) setGroceryItems(fresh);
      }
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Pantry sync failed"}`);
    } finally {
      setIsSyncing(false);
    }
  }, [isSyncing, showToast]);

  return {
    groceryItems,
    setGroceryItems,
    activeCategory,
    setActiveCategory,
    isSyncing,
    loading,
    error,
    recentlyBought,
    clearRecentlyBought,
    addGroceryItem,
    toggleGroceryNeeded,
    deleteGroceryItem,
    updateGroceryItem,
    syncMealToGrocery,
    syncPantryToGrocery,
  };
}
