/* eslint-disable react-hooks/set-state-in-effect */
import { useState, useEffect } from "react";
import { db } from "@/db";
import { GroceryItem, Meal } from "@/types/meals";
import { initialGroceryItems, groceryCategories } from "@/data/meals";
import { mealSyncService } from "@/services/mealSync";

const GROCERY_KEY = "consuela-grocery";
const RECENTLY_BOUGHT_KEY = "consuela-recently-bought";

const loadJSON = <T,>(key: string, fallback: T): T => {
  if (typeof window === "undefined") return fallback;
  try { const s = localStorage.getItem(key); return s ? JSON.parse(s) : fallback; }
  catch { return fallback; }
};

const normalizeName = (name: string) => name.toLowerCase().replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim();

const guessCategory = (name: string) => {
  const lower = name.toLowerCase();
  if (lower.includes('banana') || lower.includes('apple') || lower.includes('spinach') || lower.includes('avocado') || lower.includes('broccoli') || lower.includes('tomato') || lower.includes('lemon') || lower.includes('onion') || lower.includes('garlic') || lower.includes('carrot') || lower.includes('pepper')) return 'produce';
  if (lower.includes('milk') || lower.includes('egg') || lower.includes('cheese') || lower.includes('yogurt') || lower.includes('butter') || lower.includes('cream')) return 'dairy';
  if (lower.includes('chicken') || lower.includes('beef') || lower.includes('pork') || lower.includes('salmon') || lower.includes('shrimp') || lower.includes('fish') || lower.includes('bacon')) return 'meat';
  if (lower.includes('pasta') || lower.includes('rice') || lower.includes('bean') || lower.includes('oil') || lower.includes('sauce') || lower.includes('flour') || lower.includes('sugar') || lower.includes('dough') || lower.includes('salsa')) return 'pantry';
  if (lower.includes('frozen')) return 'frozen';
  if (lower.includes('chip') || lower.includes('snack') || lower.includes('cereal')) return 'snacks';
  if (lower.includes('coffee') || lower.includes('juice') || lower.includes('soda') || lower.includes('water')) return 'beverages';
  if (lower.includes('soap') || lower.includes('cleaner') || lower.includes('tissue') || lower.includes('detergent')) return 'household';
  return 'pantry';
};

const parseManualGroceryInput = (input: string) => {
  const cleaned = input.trim().replace(/^add\s+/i, '').replace(/\s+to\s+(grocery|grocery list|list)$/i, '');
  const match = cleaned.match(/^(\d+(?:\.\d+)?)\s+(.+)$/);
  if (match) return { name: match[2].trim(), quantity: match[1] };
  return { name: cleaned, quantity: '' };
};

export function useGrocery(showToast: (msg: string) => void, plannedMeals: Meal[] = []) {
  const [groceryItems, setGroceryItems] = useState<GroceryItem[]>([]);
  const [activeCategory, setActiveCategory] = useState("all");
  const [isSyncing, setIsSyncing] = useState(false);
  const [recentlyBought, setRecentlyBought] = useState<{ name: string; emoji: string; category: string }[]>([]);

  const mapDbToGrocery = (g: any): GroceryItem => {
    const cat = g.category || "pantry";
    const catDef = groceryCategories.find(c => c.id === cat);
    return {
      id: g.id,
      name: g.name,
      emoji: g.emoji || catDef?.emoji || "📦",
      category: cat,
      aisle: g.aisle || "1",
      quantity: g.quantity,
      notes: g.notes,
      priority: g.priority || "medium",
      needed: g.needed !== false,
      manualOverride: g.manualOverride,
      lastSyncedAt: g.lastSyncedAt,
      source: g.source,
      autoGenerated: g.autoGenerated,
    };
  };

  useEffect(() => {
    const grocery = db.selectGrocery();
    const defaultGrocery = grocery.length ? grocery.map(mapDbToGrocery) : initialGroceryItems;
    const savedGrocery = loadJSON<GroceryItem[]>(GROCERY_KEY, defaultGrocery);
    setGroceryItems(savedGrocery);
    const savedRecent = loadJSON<{ name: string; emoji: string; category: string }[]>(RECENTLY_BOUGHT_KEY, []);
    setRecentlyBought(savedRecent);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (groceryItems.length) localStorage.setItem(GROCERY_KEY, JSON.stringify(groceryItems));
  }, [groceryItems]);

  useEffect(() => {
    localStorage.setItem(RECENTLY_BOUGHT_KEY, JSON.stringify(recentlyBought));
  }, [recentlyBought]);

  const addGroceryItem = async (
    name: string,
    category: string,
    priority: "low" | "medium" | "high",
    emojiOverride?: string,
    quantity = "",
    notes = ""
  ) => {
    const trimmed = name.trim();
    if (!trimmed) return false;

    const catDef = groceryCategories.find(c => c.id === category);
    const itemEmoji = emojiOverride || catDef?.emoji || "📦";
    const aisle = catDef?.aisles?.[0]?.split('-')[0] || "1";
    let didAdd = false;
    let isDuplicate = false;

    const existing = groceryItems.find(i => normalizeName(i.name) === normalizeName(trimmed));

    if (existing) {
      isDuplicate = true;
      await db.upsertGroceryItem({ ...existing, needed: true, quantity: quantity || existing.quantity || "", notes: notes || existing.notes || "" });
      setGroceryItems(prev => prev.map(i => i.id === existing.id ? { ...i, needed: true, quantity: quantity || i.quantity, notes: notes || i.notes } : i));
    } else {
      didAdd = true;
      await db.upsertGroceryItem({ name: trimmed, category, aisle, quantity: quantity.trim(), notes: notes.trim(), priority, needed: true, source: "manual", autoGenerated: false, emoji: itemEmoji });
      setGroceryItems(prev => [
        ...prev,
        {
          id: Date.now(),
          name: trimmed,
          emoji: itemEmoji,
          category,
          aisle,
          quantity: quantity.trim(),
          notes: notes.trim(),
          priority,
          needed: true,
          source: "manual",
          autoGenerated: false,
        },
      ]);
    }

    setRecentlyBought(prev => {
      const filtered = prev.filter(r => normalizeName(r.name) !== normalizeName(trimmed));
      return [{ name: trimmed, emoji: itemEmoji, category }, ...filtered].slice(0, 8);
    });
    showToast(isDuplicate ? `🛒 ${trimmed} is already on your list` : `🛒 Added ${trimmed}`);
    return didAdd || isDuplicate;
  };

  const clearRecentlyBought = () => {
    setRecentlyBought([]);
    localStorage.removeItem(RECENTLY_BOUGHT_KEY);
  };

  const toggleGroceryNeeded = async (id: number) => {
    const item = groceryItems.find(i => i.id === id);
    if (!item) return;
    await db.upsertGroceryItem({ ...item, needed: !item.needed, id: item.id });
    setGroceryItems(prev => prev.map(i => i.id === id ? { ...i, needed: !i.needed } : i));
  };

  const deleteGroceryItem = async (id: number) => {
    await db.deleteGroceryItem(id);
    setGroceryItems(prev => prev.filter(i => i.id !== id));
  };

  const updateGroceryItem = async (id: number, updates: { name: string; quantity: string; notes: string }) => {
    const item = groceryItems.find(i => i.id === id);
    const trimmedName = updates.name.trim();
    if (!item || !trimmedName) return;
    await db.upsertGroceryItem({ ...item, id, name: trimmedName, quantity: updates.quantity.trim(), notes: updates.notes.trim() });
    setGroceryItems(prev => prev.map(i => i.id === id ? { ...i, name: trimmedName, quantity: updates.quantity.trim(), notes: updates.notes.trim() } : i));
  };

  const mergeFreshIntoState = (fresh: GroceryItem[]) => {
    setGroceryItems(prev => {
      if (!fresh.length) return prev;
      const prevByName = new Map(prev.map(i => [normalizeName(i.name || ""), i]));
      const freshByName = new Map(fresh.map(i => [normalizeName(i.name || ""), i]));
      const merged: GroceryItem[] = prev.map(i => freshByName.get(normalizeName(i.name || "")) || i);
      for (const f of fresh) {
        if (!prevByName.has(normalizeName(f.name || ""))) merged.push(f);
      }
      return merged;
    });
  };

  const syncMealToGrocery = async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncMealPlanToGrocery("demo", plannedMeals);
      showToast(`✅ Synced +${result.added} items to grocery`);
      const fresh = db.selectGrocery().map(mapDbToGrocery);
      mergeFreshIntoState(fresh);
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Sync failed"}`);
    } finally { setIsSyncing(false); }
  };

  const syncPantryToGrocery = async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncPantryToGrocery("demo");
      showToast(`✅ Pantry synced: +${result.added} added, ${result.updated} updated`);
      const fresh = db.selectGrocery().map(mapDbToGrocery);
      mergeFreshIntoState(fresh);
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Pantry sync failed"}`);
    } finally { setIsSyncing(false); }
  };

  return {
    groceryItems,
    setGroceryItems,
    activeCategory,
    setActiveCategory,
    isSyncing,
    recentlyBought,
    clearRecentlyBought,
    addGroceryItem,
    toggleGroceryNeeded,
    deleteGroceryItem,
    updateGroceryItem,
    syncMealToGrocery,
    syncPantryToGrocery,
    parseManualGroceryInput,
    guessCategory,
  };
}
