import { useState, useEffect } from "react";
import { db } from "@/db";
import { GroceryItem } from "@/types/meals";
import { initialGroceryItems, groceryCategories } from "@/data/meals";
import { mealSyncService } from "@/services/mealSync";

const GROCERY_KEY = "consuela-grocery";

const loadJSON = <T,>(key: string, fallback: T): T => {
  if (typeof window === "undefined") return fallback;
  try { const s = localStorage.getItem(key); return s ? JSON.parse(s) : fallback; }
  catch { return fallback; }
};

export function useGrocery(showToast: (msg: string) => void) {
  const [groceryItems, setGroceryItems] = useState<GroceryItem[]>([]);
  const [activeCategory, setActiveCategory] = useState("all");
  const [isSyncing, setIsSyncing] = useState(false);

  const mapDbToGrocery = (g: any): GroceryItem => {
    const cat = g.category || "pantry";
    const catDef = groceryCategories.find(c => c.id === cat);
    return { 
      id: g.id, 
      name: g.name, 
      emoji: catDef?.emoji || "📦", 
      category: cat, 
      aisle: g.aisle || "1", 
      quantity: g.quantity, 
      notes: g.notes, 
      priority: g.priority || "medium", 
      needed: g.needed !== false, 
      manualOverride: g.manualOverride, 
      lastSyncedAt: g.lastSyncedAt, 
      source: g.source, 
      autoGenerated: g.autoGenerated 
    };
  };

  useEffect(() => {
    const grocery = db.selectGrocery();
    const defaultGrocery = grocery.length ? grocery.map(mapDbToGrocery) : initialGroceryItems;
    const savedGrocery = loadJSON(GROCERY_KEY, defaultGrocery);
    setGroceryItems(savedGrocery);
  }, []);

  useEffect(() => {
    if (groceryItems.length) localStorage.setItem(GROCERY_KEY, JSON.stringify(groceryItems));
  }, [groceryItems]);

  const addGroceryItem = (name: string, category: string, priority: "low" | "medium" | "high") => {
    const trimmed = name.trim();
    if (!trimmed) return;
    const catDef = groceryCategories.find(c => c.id === category);
    db.upsertGroceryItem({ name: trimmed, category, aisle: "1", quantity: "", notes: "", priority, needed: true, source: "manual", autoGenerated: false });
    const fresh = db.selectGrocery().map(mapDbToGrocery);
    setGroceryItems(fresh.length ? fresh : [...groceryItems, { id: Date.now(), name: trimmed, emoji: catDef?.emoji || "📦", category, aisle: "1", priority, needed: true }]);
    showToast(`🛒 Added ${trimmed}`);
  };

  const toggleGroceryNeeded = (id: number) => {
    const item = groceryItems.find(i => i.id === id);
    if (!item) return;
    db.upsertGroceryItem({ ...item, needed: !item.needed, id: item.id });
    setGroceryItems(prev => prev.map(i => i.id === id ? { ...i, needed: !i.needed } : i));
  };

  const deleteGroceryItem = (id: number) => {
    db.deleteGroceryItem(id);
    setGroceryItems(prev => prev.filter(i => i.id !== id));
  };

  const updateGroceryItem = (id: number, updates: { name: string; quantity: string; notes: string }) => {
    const item = groceryItems.find(i => i.id === id);
    if (!item || !updates.name.trim()) return;
    db.upsertGroceryItem({ ...item, id, name: updates.name.trim(), quantity: updates.quantity, notes: updates.notes });
    setGroceryItems(prev => prev.map(i => i.id === id ? { ...i, name: updates.name.trim(), quantity: updates.quantity, notes: updates.notes } : i));
  };

  const syncMealToGrocery = async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncMealPlanToGrocery("demo");
      showToast(`✅ Synced +${result.added} items to grocery`);
      const fresh = db.selectGrocery().map(mapDbToGrocery);
      if (fresh.length) setGroceryItems(fresh);
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Sync failed"}`);
    } finally { setIsSyncing(false); }
  };

  const syncPantryToGrocery = async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      const result = await mealSyncService.syncPantryToGrocery("demo");
      showToast(`✅ Pantry synced: ${result.updated} updated`);
      const fresh = db.selectGrocery().map(mapDbToGrocery);
      if (fresh.length) setGroceryItems(fresh);
    } catch (e: any) {
      showToast(`❌ ${e?.message || "Pantry sync failed"}`);
    } finally { setIsSyncing(false); }
  };

  return {
    groceryItems,
    setGroceryItems,
    activeCategory,
    setActiveCategory,
    isSyncing,
    addGroceryItem,
    toggleGroceryNeeded,
    deleteGroceryItem,
    updateGroceryItem,
    syncMealToGrocery,
    syncPantryToGrocery,
  };
}
