import { useState, useEffect, useCallback } from "react";
import { Meal } from "@/types/meals";
import { defaultMeals, mealIdeas } from "@/data/meals";

export function useMeals() {
  const [meals, setMeals] = useState<Meal[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeDay, setActiveDay] = useState(
    new Date().toLocaleDateString("en-US", { weekday: "short" })
  );

  // AI Suggestions
  const [aiMealIdeas, setAiMealIdeas] = useState<
    Array<{ name: string; emoji: string; tags: string[] }>
  >([]);
  const [aiMealLoading, setAiMealLoading] = useState(false);
  const [showAiSuggestions, setShowAiSuggestions] = useState(false);

  // Fetch meals from API on mount
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        setLoading(true);
        const res = await fetch("/api/meals");
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        const items: Meal[] = (data.meals || []).map((m: any) => ({
          id: m.id,
          name: m.name,
          emoji: m.emoji || "🍽️",
          time: m.time ?? m.scheduledFor ?? "Mon",
          mealType: m.mealType,
          prepTime: m.prepTime || "30 min",
          tags: typeof m.tags === "string"
            ? m.tags
              ? JSON.parse(m.tags)
              : []
            : m.tags || [],
          ingredients: typeof m.ingredients === "string"
            ? m.ingredients
              ? JSON.parse(m.ingredients)
              : []
            : m.ingredients || [],
          servings: m.servings ?? 4,
          calories: m.calories ?? 500,
          protein: m.protein,
          carbs: m.carbs,
          fat: m.fat,
          instructions: m.instructions,
          autoGenerated: m.autoGenerated,
        }));
        if (!cancelled) {
          setMeals(items.length > 0 ? items : defaultMeals);
          setError(null);
        }
      } catch (e: any) {
        if (!cancelled) {
          // Fall back to defaults on error
          setMeals(defaultMeals);
          setError(e?.message || "Failed to load meals");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const generateAiMeals = useCallback(async () => {
    setAiMealLoading(true);
    setShowAiSuggestions(true);
    try {
      // Fetch pantry items from API instead of db
      let pantryNames = "";
      try {
        const pantryRes = await fetch("/api/pantry");
        if (pantryRes.ok) {
          const pantryData = await pantryRes.json();
          pantryNames = (pantryData.pantry || [])
            .map((p: any) => p.name)
            .join(", ");
        }
      } catch {
        // ignore pantry fetch failure
      }

      const res = await fetch("/api/hermes/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: `Suggest 4 meal ideas for a family of 7 (kids ages 5-14). Pantry has: ${pantryNames || "basic ingredients"}. Return as JSON: {"actions":[{"type":"meal","title":"Meal Name","detail":"Prep time · Kid-friendly tags","emoji":"🍝"}]}. Make them varied, practical, and family-friendly.`,
        }),
      });
      const data = await res.json();
      const actions = data.actions || [];
      const ideas = actions
        .filter((a: any) => a.type === "meal")
        .map((a: any) => ({
          name: a.title,
          emoji: a.emoji || "🍽️",
          tags:
            a.detail
              ?.split("·")
              .map((t: string) => t.trim())
              .filter(Boolean) || ["Family"],
        }));
      setAiMealIdeas(ideas.length > 0 ? ideas : mealIdeas);
    } catch {
      setAiMealIdeas(mealIdeas);
    }
    setAiMealLoading(false);
  }, []);

  const deleteMeal = useCallback(
    async (id: string | number) => {
      try {
        await fetch(`/api/meals?id=${id}`, { method: "DELETE" });
      } catch {
        // Still remove locally even if API fails
      }
      setMeals((prev) => prev.filter((m) => m.id !== id));
    },
    []
  );

  const addMeal = useCallback(async (meal: Omit<Meal, "id">) => {
    try {
      const res = await fetch("/api/meals", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(meal),
      });
      if (res.ok) {
        const data = await res.json();
        const newMeal = {
          id: data.meal.id,
          name: data.meal.name,
          emoji: data.meal.emoji || "🍽️",
          time: data.meal.time ?? data.meal.scheduledFor ?? "Mon",
          mealType: data.meal.mealType,
          prepTime: data.meal.prepTime || "30 min",
          tags: typeof data.meal.tags === "string"
            ? data.meal.tags
              ? JSON.parse(data.meal.tags)
              : []
            : data.meal.tags || [],
          ingredients: typeof data.meal.ingredients === "string"
            ? data.meal.ingredients
              ? JSON.parse(data.meal.ingredients)
              : []
            : data.meal.ingredients || [],
          servings: data.meal.servings ?? 4,
          calories: data.meal.calories ?? 500,
          protein: data.meal.protein,
          carbs: data.meal.carbs,
          fat: data.meal.fat,
          instructions: data.meal.instructions,
          autoGenerated: data.meal.autoGenerated,
        } as Meal;
        setMeals((prev) => [...prev, newMeal]);
        return newMeal;
      }
    } catch {
      // Fall through
    }
    return null;
  }, []);

  const updateMeal = useCallback(
    async (id: string | number, updates: Partial<Meal>) => {
      try {
        await fetch("/api/meals", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id, ...updates }),
        });
      } catch {
        // Still update locally
      }
      setMeals((prev) =>
        prev.map((m) => (m.id === id ? { ...m, ...updates } : m))
      );
    },
    []
  );

  const activeMeals = meals.filter((m) => m.time === activeDay);

  return {
    meals,
    setMeals,
    activeDay,
    setActiveDay,
    activeMeals,
    deleteMeal,
    addMeal,
    updateMeal,
    loading,
    error,
    aiMealIdeas,
    aiMealLoading,
    showAiSuggestions,
    generateAiMeals,
  };
}
