import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const meals = sqliteTable('meals', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  recipeId: text('recipe_id'),
  name: text('name').notNull(),
  emoji: text('emoji').notNull(),
  scheduledFor: text('scheduled_for').notNull(),
  prepTime: text('prep_time'),
  tags: text('tags'),
  ingredients: text('ingredients'),
  servings: integer('servings').notNull().default(4),
  calories: integer('calories'),
  notes: text('notes'),
  autoGenerated: integer('auto_generated', { mode: 'boolean' }).notNull().default(false),
  lastSyncedAt: text('last_synced_at'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const ingredients = sqliteTable('ingredients', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull().unique(),
  unit: text('unit').notNull(),
  nutritionPerUnit: text('nutrition_per_unit'),
  embeddingVector: text('embedding_vector'),
  commonSubstitutes: text('common_substitutes'),
  category: text('category'),
  createdAt: text('created_at').notNull(),
});

export const pantryItems = sqliteTable('pantry_items', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  ingredientId: integer('ingredient_id').references(() => ingredients.id),
  name: text('name').notNull(),
  quantity: real('quantity'),
  unit: text('unit'),
  status: text('status').notNull(),
  expirationDate: text('expiration_date'),
  lastUpdated: text('last_updated').notNull(),
  createdAt: text('created_at').notNull(),
});

export const groceryListItems = sqliteTable('grocery_list_items', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  ingredientId: integer('ingredient_id').references(() => ingredients.id),
  name: text('name').notNull(),
  emoji: text('emoji'),
  category: text('category').notNull(),
  aisle: text('aisle'),
  quantity: text('quantity'),
  notes: text('notes'),
  priority: text('priority').notNull(),
  needed: integer('needed', { mode: 'boolean' }).notNull().default(true),
  source: text('source').notNull(),
  autoGenerated: integer('auto_generated', { mode: 'boolean' }).notNull().default(true),
  manualOverride: integer('manual_override', { mode: 'boolean' }).notNull().default(false),
  lastSyncedAt: text('last_synced_at'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
