export interface Meal {
  id: number;
  name: string;
  emoji: string;
  time: string;
  mealType?: "breakfast" | "lunch" | "dinner" | "snack";
  prepTime: string;
  tags: string[];
  ingredients: string[];
  servings: number;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  instructions?: string;
  autoGenerated?: boolean;
  recipeId?: string;
  recipeSnapshotAt?: string;
  weekOf?: string;
  date?: string;
}

export interface Recipe {
  id: number;
  name: string;
  emoji: string;
  prepTime: string;
  cookTime?: string;
  tags: string[];
  ingredients: string[];
  instructions: string;
  servings: number;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  source?: string;
  sourceUrl?: string;
  createdAt: string;
  favorite?: boolean;
  difficulty?: "Easy" | "Medium" | "Cozy";
  rating?: number;
  image?: string;
}

export interface PantryItem {
  id: number | string;
  item: string;
  name?: string;
  status: "plenty" | "low" | "out";
  quantity?: number;
  unit?: string;
}

export interface GroceryItem {
  id: number | string;
  userId?: string;
  name: string;
  emoji: string;
  category: string;
  aisle?: string;
  quantity?: string;
  notes?: string;
  priority: "low" | "medium" | "high";
  needed: boolean;
  manualOverride?: boolean;
  lastSyncedAt?: string;
  source?: string;
  autoGenerated?: boolean;
  updatedAt?: string;
  quantityValue?: number;
  unit?: string;
  pinned?: boolean;
}

export type Tab = "plan" | "shop" | "stock";
