export interface Meal {
  id: number;
  name: string;
  emoji: string;
  time: string;
  mealType?: "breakfast" | "lunch" | "dinner" | "snack";
  prepTime: string;
  tags: string[];
  ingredients: string[];
  servings: number;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  instructions?: string;
  autoGenerated?: boolean;
}

export interface Recipe {
  id: number;
  name: string;
  emoji: string;
  prepTime: string;
  cookTime?: string;
  tags: string[];
  ingredients: string[];
  instructions: string;
  servings: number;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  source?: string;
  createdAt: string;
  favorite?: boolean;
  difficulty?: "Easy" | "Medium" | "Cozy";
  rating?: number;
  image?: string;
}

export interface PantryItem {
  id: number;
  item: string;
  status: "plenty" | "low" | "out";
}

export interface GroceryItem {
  id: number;
  name: string;
  emoji: string;
  category: string;
  aisle: string;
  quantity?: string;
  notes?: string;
  priority: "low" | "medium" | "high";
  needed: boolean;
  manualOverride?: boolean;
  lastSyncedAt?: string;
  source?: string;
  autoGenerated?: boolean;
}

export type Tab = "meals" | "grocery" | "pantry" | "recipes";
