// Embeds the ai/ boot files (SOUL.md, IDENTITY.md, TOOLS.md, KID.md) into a
// generated TypeScript module so the chat route composes its system prompt
// from the same version-controlled persona docs a Hermes profile would load
// at startup. Runs at prebuild (`write-version.mjs` runs first — see
// package.json "prebuild"), so a stale persona fails the build, not prod.
// Mirrors Hermes agent/prompt_builder.py: SOUL.md is the identity layer,
// AGENTS/context files ride behind it.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const AI_DIR = join(ROOT, "ai");
const OUT = join(ROOT, "src", "lib", "ai-boot.generated.ts");

function load(name) {
  try {
    return readFileSync(join(AI_DIR, name), "utf8").trim();
  } catch {
    console.error(`[write-ai-boot] MISSING ai/${name} — the boot files are required.`);
    process.exit(1);
  }
}

const files = {
  SOUL_MD: load("SOUL.md"),
  IDENTITY_MD: load("IDENTITY.md"),
  TOOLS_MD: load("TOOLS.md"),
  KID_MD: load("KID.md"),
};

// Guard: the kid toolset documented in KID.md must match the runtime
// allowlist in src/lib/hermes-tools.ts exactly — doc drift is a bug.
const kidDoc = files.KID_MD;
const toolsSrc = readFileSync(join(ROOT, "src", "lib", "hermes-tools.ts"), "utf8");
const runtimeKid = toolsSrc
  .split("KID_TOOL_NAMES: ReadonlySet<string> = new Set([")[1]
  ?.split("]);")[0]
  ?.split('"')
  .filter((s) => /^[a-z_]+$/.test(s) && s !== "get" && s !== "set" && s.length > 3)
  .sort() ?? [];
for (const name of runtimeKid) {
  if (!kidDoc.includes(`\`${name}\``)) {
    console.error(
      `[write-ai-boot] DRIFT: tool "${name}" is in the runtime KID_TOOL_NAMES but missing from ai/KID.md's toolset list.`
    );
    process.exit(1);
  }
}

const body = `// GENERATED by scripts/write-ai-boot.mjs at prebuild — do not edit by hand.
// Source of truth: ai/SOUL.md, ai/IDENTITY.md, ai/TOOLS.md, ai/KID.md.
export const AI_BOOT = ${JSON.stringify(files, null, 2)} as const;
`;

writeFileSync(OUT, body, "utf8");
console.log(
  `[write-ai-boot] embedded ${Object.entries(files)
    .map(([k, v]) => `${k}(${Math.ceil(v.length / 1024)}kb)`)
    .join(" ")} -> ${OUT}`
);
