// @vitest-environment jsdom
// Task 10 — the ✨ Generate / Suggest buttons send planner INTENTS, not
// handcrafted prompts: no "family of 7" facts, no "Caspian" fallback, and the
// request bodies are exactly {agent:"planner", intent, options} (no `message`).
// generateWeeklyPlan/generateAiMeals are driven through the real useMeals
// harness with a captured fetch; the tasks-page mappings run through the
// pure mappers the page now uses (mounting the 2,200-line page is out of
// scope) + a source scan pins the actual request bodies in tasks/page.tsx.
import { describe, it, expect, vi, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { createRoot } from "react-dom/client";
import { act, useEffect } from "react";

(globalThis as unknown as { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const h = vi.hoisted(() => ({
  meals: [] as any[],
}));

vi.mock("@/db", () => ({
  db: {
    gatewayReadStatus: async (collection: string) => {
      if (collection === "meal_plan_entries") {
        return { items: h.meals.map((m) => ({ ...m })), blocked: false };
      }
      return { items: [], blocked: false };
    },
    selectMeals: async () => h.meals.map((m) => ({ ...m })),
    selectPantry: async () => [{ name: "Eggs" }, { name: "Flour" }],
    insertMeal: async (meal: any) => {
      h.meals.push({ ...meal });
      return { ...meal };
    },
    updateMeal: async () => null,
    deleteMeal: async () => false,
    mealsStore: h.meals,
  },
}));

import { useMeals } from "@/hooks/useMeals";
import { mapTaskIdeas, mapRewardIdeas } from "@/lib/ai-suggestions";

let mealsResult: any;
function Harness() {
  const meals = useMeals();
  useEffect(() => {
    mealsResult = meals;
  });
  return null;
}

let fetchCalls: Array<{ url: string; body: any }>;
let plannerResponse: () => any;

async function mount() {
  const el = document.createElement("div");
  document.body.appendChild(el);
  await act(async () => {
    createRoot(el).render(<Harness />);
  });
  await act(async () => {
    await new Promise((r) => setTimeout(r, 20));
  });
}

beforeEach(async () => {
  h.meals = [];
  mealsResult = null;
  fetchCalls = [];
  plannerResponse = () => ({ ok: true, result: { meal_plan: [] } });
  localStorage.clear();
  vi.stubGlobal("fetch", async (url: string, init: any) => {
    fetchCalls.push({ url: String(url), body: JSON.parse(init.body) });
    return { ok: true, json: async () => plannerResponse() };
  });
  await mount();
});

describe("generateWeeklyPlan posts a planner body and fills slots", () => {
  it("body is exactly {agent:'planner',intent:'meal_week',options:{weekOf,days}} — no message", async () => {
    plannerResponse = () => ({
      ok: true,
      intent: "meal_week",
      result: {
        meal_plan: [
          { day: "Mon", mealType: "dinner", name: "Sheet-pan tacos", emoji: "🌮", tags: ["Kid-friendly"], prepTime: "20 min" },
        ],
      },
    });
    await act(async () => {
      await mealsResult.generateWeeklyPlan("2026-09-14", false, ["Mon"]);
    });
    expect(fetchCalls).toHaveLength(1);
    expect(fetchCalls[0].url).toBe("/api/hermes/chat");
    expect(fetchCalls[0].body).toEqual({
      agent: "planner",
      intent: "meal_week",
      options: { weekOf: "2026-09-14", days: ["Mon"] },
    });
    expect(fetchCalls[0].body.message).toBeUndefined();
    expect(fetchCalls[0].body.persist).toBeUndefined();
  });

  it("maps result.meal_plan into meals (autoGenerated, weekOf) and keeps the occupied guard", async () => {
    h.meals.push({ id: "9", name: "Planned tonight", time: "Mon", mealType: "dinner", weekOf: "2026-09-14" });
    await act(async () => {
      window.dispatchEvent(new CustomEvent("consuela-data-refreshed"));
      await new Promise((r) => setTimeout(r, 20));
    });
    plannerResponse = () => ({
      ok: true,
      result: {
        meal_plan: [
          { day: "Mon", mealType: "dinner", name: "Overwritten?" },
          { day: "Tue", mealType: "lunch", name: "Soup", prepTime: "15 min" },
        ],
      },
    });
    await act(async () => {
      await mealsResult.generateWeeklyPlan("2026-09-14", false);
    });
    const names = h.meals.map((m) => m.name);
    expect(names).not.toContain("Overwritten?");
    expect(names).toContain("Soup");
    const soup = h.meals.find((m) => m.name === "Soup");
    expect(soup).toMatchObject({ time: "Tue", mealType: "lunch", weekOf: "2026-09-14", autoGenerated: true });
  });

  it("{ok:false} from the route surfaces the weeklyPlanError pill and saves nothing", async () => {
    plannerResponse = () => ({ ok: false, reason: "invalid_model_output" });
    await act(async () => {
      await mealsResult.generateWeeklyPlan("2026-09-14", false);
    });
    expect(mealsResult.weeklyPlanError).toBeTruthy();
    expect(h.meals).toHaveLength(0);
  });
});

describe("generateAiMeals posts a meal_ideas intent and maps result.actions", () => {
  it("body is {agent:'planner',intent:'meal_ideas'} — no message, no pantry prompt", async () => {
    plannerResponse = () => ({
      ok: true,
      result: {
        actions: [
          { type: "meal", title: "Sheet-pan gnocchi", detail: "One pan · 25 min", emoji: "🍝" },
        ],
      },
    });
    await act(async () => {
      await mealsResult.generateAiMeals();
    });
    expect(fetchCalls).toHaveLength(1);
    expect(fetchCalls[0].url).toBe("/api/hermes/chat");
    expect(fetchCalls[0].body).toEqual({ agent: "planner", intent: "meal_ideas" });
    expect(fetchCalls[0].body.message).toBeUndefined();
    expect(mealsResult.aiMealIdeas).toEqual([
      { name: "Sheet-pan gnocchi", emoji: "🍝", tags: ["One pan", "25 min"] },
    ]);
  });

  it("{ok:false} keeps the honest aiMealError, no ideas", async () => {
    plannerResponse = () => ({ ok: false, reason: "provider_unavailable" });
    await act(async () => {
      await mealsResult.generateAiMeals();
    });
    expect(mealsResult.aiMealIdeas).toEqual([]);
    expect(mealsResult.aiMealError).toBeTruthy();
  });
});

describe("task/reward suggestion mappers (used by the Tasks page buttons)", () => {
  const members = [
    { name: "Caspian", fullName: "Caspian Garcia", emoji: "🧒", role: "child" },
    { name: "Aurora", fullName: "Aurora Garcia", emoji: "👧", role: "child" },
  ];

  it("mapTaskIdeas builds rows from validated actions and SKIPS unknown assignees (no Caspian fallback)", () => {
    let n = 0;
    const out = mapTaskIdeas(
      [
        { type: "task", title: "Fold laundry", assignee: "Caspian", points: 8, emoji: "🧺" },
        { type: "task", title: "Water the plants", assignee: "Nobody Real", points: 5 },
        { type: "task", title: "No assignee at all", points: 6 },
      ],
      members,
      { nextId: () => ++n, today: "2026-09-14" },
    );
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      title: "Fold laundry",
      assignee: "Caspian Garcia",
      assigneeEmoji: "🧒",
      points: 8,
      due: "2026-09-14",
      category: "AI Suggested",
      priority: "low",
    });
  });

  it("mapTaskIdeas points default + priority bands survive mapping", () => {
    const out = mapTaskIdeas(
      [{ type: "task", title: "Deep-clean garage", assignee: "Aurora" }],
      members,
      { nextId: () => 1, today: "2026-09-14" },
    );
    expect(out[0].points).toBe(8);
    const hi = mapTaskIdeas(
      [{ type: "task", title: "Yard work", assignee: "Aurora", points: 15 }],
      members,
      { nextId: () => 2, today: "2026-09-14" },
    );
    expect(hi[0].priority).toBe("high");
  });

  it("mapRewardIdeas prices from points, no detail-string regex", () => {
    const out = mapRewardIdeas([
      { type: "reward", title: "Extra screen time", points: 60, emoji: "📱" },
      { type: "reward", title: "Movie night" },
    ]);
    expect(out.map((r) => [r.name, r.cost, r.emoji])).toEqual([
      ["Extra screen time", 60, "📱"],
      ["Movie night", 50, "🎁"],
    ]);
  });
});

describe("source scan: handcrafted prompts are gone from the Tasks page", () => {
  const src = readFileSync(resolve(__dirname, "../../src/app/tasks/page.tsx"), "utf8");

  it("no 'family of 7' fact, no || \"Caspian\" fallback, no extractActions", () => {
    expect(src).not.toMatch(/family of 7/);
    expect(src).not.toMatch(/\|\|\s*"Caspian"/);
    expect(src).not.toMatch(/extractActions/);
  });

  it("generateAiTasks/generateAiRewards post planner bodies (no `message:` strings)", () => {
    const grab = (name: string) => {
      const start = src.indexOf(`const ${name} = async`);
      expect(start, name).toBeGreaterThan(-1);
      const end = src.indexOf("\n  const ", start + 1);
      return src.slice(start, end);
    };
    const tasks = grab("generateAiTasks");
    const rewards = grab("generateAiRewards");
    for (const body of [tasks, rewards]) {
      expect(body).toContain('agent: "planner"');
      expect(body).not.toMatch(/message:/);
    }
    expect(tasks).toContain('intent: "task_ideas"');
    expect(rewards).toContain('intent: "reward_ideas"');
  });
});
