import { describe, it, expect, vi, beforeEach } from "vitest";

const h = vi.hoisted(() => ({ state: { grocery: [] as any[], pantry: [] as any[], meals: [] as any[] } }));

vi.mock("@/db", () => ({
  db: {
    selectGrocery: async () => h.state.grocery.map(r => ({ ...r })),
    selectPantry: async () => h.state.pantry.map(r => ({ ...r })),
    selectMeals: async () => h.state.meals.map(r => ({ ...r })),
    upsertGroceryItem: async (item: any) => {
      const byId = item.id != null ? h.state.grocery.find(g => String(g.id) === String(item.id)) : undefined;
      const existing = byId || h.state.grocery.find(g => g.name?.toLowerCase() === item.name?.toLowerCase());
      const { id: _omit, ...data } = item;
      if (existing) { Object.assign(existing, data); return { ...existing }; }
      if (!data.name) return null;
      const rec = { id: `g_${h.state.grocery.length + 1}`, ...data };
      h.state.grocery.push(rec);
      return { ...rec };
    },
  },
}));

import { mealSyncService } from "@/services/mealSync";

describe("mealSyncService honest updates", () => {
  beforeEach(() => {
    h.state.grocery = [];
    h.state.pantry = [];
    h.state.meals = [];
  });

  it("syncPantryToGrocery unchecks a needed grocery row when pantry has plenty (BUG-3)", async () => {
    h.state.grocery.push({ id: "g_1", name: "Milk", needed: true, source: "meal-plan" });
    h.state.pantry.push({ id: "p_1", name: "Milk", status: "plenty" });
    const result = await mealSyncService.syncPantryToGrocery("demo");
    expect(h.state.grocery[0].needed).toBe(false);
    expect(result.updated).toBe(1);
  });

  it("syncMealPlanToGrocery updates the quantity of an existing auto item (BUG-3)", async () => {
    h.state.grocery.push({ id: "g_1", name: "Chicken breast", needed: true, source: "meal-plan", autoGenerated: true });
    h.state.meals.push({ id: 1, name: "Dinner", time: "Mon", ingredients: ["3 lb Chicken breast"], servings: 4 });
    const result = await mealSyncService.syncMealPlanToGrocery("demo");
    expect(h.state.grocery[0].quantity).toBe("3 lb");
    expect(result.updated).toBe(1);
    expect(result.added).toBe(0);
  });

  it("reports zero updates when nothing matches (no lying counts)", async () => {
    h.state.grocery.push({ id: "g_1", name: "Milk", needed: true, source: "manual" });
    h.state.pantry.push({ id: "p_1", name: "Milk", status: "plenty" });
    const result = await mealSyncService.syncPantryToGrocery("demo");
    expect(result.updated).toBe(0);
    expect(h.state.grocery[0].needed).toBe(true);
  });
});
